// Tour de Cicle Indoor - Dataset completo
// Gerado automaticamente a partir da planilha oficial

const PONTOS_RANKING = [25, 20, 17, 15, 13, 11, 9, 7, 5, 3, 1];

const ATLETAS = [
  {
    "atleta": "Adriana Caldas",
    "academia": "PULSE",
    "equipe": "PRO FEMININO",
    "categoria": "Feminino",
    "ftp_final": null,
    "ftp_final_s": null,
    "montanha": null,
    "montanha_s": null,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": "00:00:00",
    "tempo_total_s": 0,
    "provas": 0,
    "completo": false,
    "pontos_montanha": 0,
    "pontos_cr10k": 0,
    "pontos_ld30k": 0,
    "pontos_total": 0,
    "pos_montanha": null,
    "pos_cr10k": null,
    "pos_ld30k": null,
    "pos_geral": null
  },
  {
    "atleta": "Adriana Melo",
    "academia": "PULSE",
    "equipe": "PRO FEMININO",
    "categoria": "Feminino",
    "ftp_final": null,
    "ftp_final_s": null,
    "montanha": null,
    "montanha_s": null,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "01:00:00",
    "ld30k_s": 3600,
    "tempo_total": "01:00:00",
    "tempo_total_s": 3600,
    "provas": 1,
    "completo": false,
    "pontos_montanha": 0,
    "pontos_cr10k": 0,
    "pontos_ld30k": 15,
    "pontos_total": 15,
    "pos_montanha": null,
    "pos_cr10k": null,
    "pos_ld30k": 4,
    "pos_geral": null
  },
  {
    "atleta": "Alê Agra",
    "academia": "PULSE",
    "equipe": "MASTER",
    "categoria": "Feminino",
    "ftp_final": null,
    "ftp_final_s": null,
    "montanha": null,
    "montanha_s": null,
    "cr10k": "00:29:28",
    "cr10k_s": 1768,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": "00:29:28",
    "tempo_total_s": 1768,
    "provas": 1,
    "completo": false,
    "pontos_montanha": 0,
    "pontos_cr10k": 11,
    "pontos_ld30k": 0,
    "pontos_total": 11,
    "pos_montanha": null,
    "pos_cr10k": 6,
    "pos_ld30k": null,
    "pos_geral": null
  },
  {
    "atleta": "Allan Oliveira",
    "academia": "AABB",
    "equipe": "SUB-26",
    "categoria": "Masculino",
    "ftp_final": null,
    "ftp_final_s": null,
    "montanha": null,
    "montanha_s": null,
    "cr10k": "00:27:41",
    "cr10k_s": 1661,
    "ld30k": "00:52:17",
    "ld30k_s": 3137,
    "tempo_total": "01:19:58",
    "tempo_total_s": 4798,
    "provas": 2,
    "completo": false,
    "pontos_montanha": 0,
    "pontos_cr10k": 17,
    "pontos_ld30k": 13,
    "pontos_total": 30,
    "pos_montanha": null,
    "pos_cr10k": 3,
    "pos_ld30k": 5,
    "pos_geral": null
  },
  {
    "atleta": "Alzinalia Lopes",
    "academia": "BT NS",
    "equipe": "MASTER",
    "categoria": "Feminino",
    "ftp_final": null,
    "ftp_final_s": null,
    "montanha": null,
    "montanha_s": null,
    "cr10k": "00:29:10",
    "cr10k_s": 1750,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": "00:29:10",
    "tempo_total_s": 1750,
    "provas": 1,
    "completo": false,
    "pontos_montanha": 0,
    "pontos_cr10k": 13,
    "pontos_ld30k": 0,
    "pontos_total": 13,
    "pos_montanha": null,
    "pos_cr10k": 5,
    "pos_ld30k": null,
    "pos_geral": null
  },
  {
    "atleta": "Sanzia Melo",
    "academia": "BT TIROL",
    "equipe": "MASTER",
    "categoria": "Feminino",
    "ftp_final": null,
    "ftp_final_s": null,
    "montanha": null,
    "montanha_s": null,
    "cr10k": "00:31:09",
    "cr10k_s": 1869,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": "00:31:09",
    "tempo_total_s": 1869,
    "provas": 1,
    "completo": false,
    "pontos_montanha": 0,
    "pontos_cr10k": 9,
    "pontos_ld30k": 0,
    "pontos_total": 9,
    "pos_montanha": null,
    "pos_cr10k": 7,
    "pos_ld30k": null,
    "pos_geral": null
  },
  {
    "atleta": "André Fernandes",
    "academia": "BT TIROL",
    "equipe": "MASTER",
    "categoria": "Masculino",
    "ftp_final": null,
    "ftp_final_s": null,
    "montanha": null,
    "montanha_s": null,
    "cr10k": "00:25:13",
    "cr10k_s": 1513,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": "00:25:13",
    "tempo_total_s": 1513,
    "provas": 1,
    "completo": false,
    "pontos_montanha": 0,
    "pontos_cr10k": 17,
    "pontos_ld30k": 0,
    "pontos_total": 17,
    "pos_montanha": null,
    "pos_cr10k": 3,
    "pos_ld30k": null,
    "pos_geral": null
  },
  {
    "atleta": "Cris Diniz",
    "academia": "PULSE",
    "equipe": "ELITE FEMININO",
    "categoria": "Feminino",
    "ftp_final": null,
    "ftp_final_s": null,
    "montanha": null,
    "montanha_s": null,
    "cr10k": "00:25:22",
    "cr10k_s": 1522,
    "ld30k": "00:46:45",
    "ld30k_s": 2805,
    "tempo_total": "01:12:07",
    "tempo_total_s": 4327,
    "provas": 2,
    "completo": false,
    "pontos_montanha": 0,
    "pontos_cr10k": 25,
    "pontos_ld30k": 25,
    "pontos_total": 50,
    "pos_montanha": null,
    "pos_cr10k": 1,
    "pos_ld30k": 1,
    "pos_geral": null
  },
  {
    "atleta": "Dani Doria",
    "academia": "BT TIROL",
    "equipe": "ELITE FEMININO",
    "categoria": "Feminino",
    "ftp_final": null,
    "ftp_final_s": null,
    "montanha": null,
    "montanha_s": null,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": null,
    "tempo_total_s": null,
    "provas": 0,
    "completo": false,
    "pontos_montanha": 0,
    "pontos_cr10k": 0,
    "pontos_ld30k": 0,
    "pontos_total": 0,
    "pos_montanha": null,
    "pos_cr10k": null,
    "pos_ld30k": null,
    "pos_geral": null
  },
  {
    "atleta": "Gabi Pereira",
    "academia": "PULSE",
    "equipe": "PRO FEMININO",
    "categoria": "Feminino",
    "ftp_final": null,
    "ftp_final_s": null,
    "montanha": null,
    "montanha_s": null,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": null,
    "tempo_total_s": null,
    "provas": 0,
    "completo": false,
    "pontos_montanha": 0,
    "pontos_cr10k": 0,
    "pontos_ld30k": 0,
    "pontos_total": 0,
    "pos_montanha": null,
    "pos_cr10k": null,
    "pos_ld30k": null,
    "pos_geral": null
  },
  {
    "atleta": "Isabel Lucena",
    "academia": "BT TIROL",
    "equipe": "SUB-26",
    "categoria": "Feminino",
    "ftp_final": null,
    "ftp_final_s": null,
    "montanha": null,
    "montanha_s": null,
    "cr10k": "00:30:05",
    "cr10k_s": 1805,
    "ld30k": "00:56:34",
    "ld30k_s": 3394,
    "tempo_total": "01:26:39",
    "tempo_total_s": 5199,
    "provas": 2,
    "completo": false,
    "pontos_montanha": 0,
    "pontos_cr10k": 15,
    "pontos_ld30k": 11,
    "pontos_total": 26,
    "pos_montanha": null,
    "pos_cr10k": 4,
    "pos_ld30k": 6,
    "pos_geral": null
  },
  {
    "atleta": "Arthur Martins",
    "academia": "BT NS",
    "equipe": "MASTER",
    "categoria": "Masculino",
    "ftp_final": null,
    "ftp_final_s": null,
    "montanha": null,
    "montanha_s": null,
    "cr10k": "00:23:29",
    "cr10k_s": 1409,
    "ld30k": "00:44:34",
    "ld30k_s": 2674,
    "tempo_total": "01:08:03",
    "tempo_total_s": 4083,
    "provas": 2,
    "completo": false,
    "pontos_montanha": 0,
    "pontos_cr10k": 25,
    "pontos_ld30k": 20,
    "pontos_total": 45,
    "pos_montanha": null,
    "pos_cr10k": 1,
    "pos_ld30k": 2,
    "pos_geral": null
  },
  {
    "atleta": "Lia",
    "academia": "BT NS",
    "equipe": "MASTER",
    "categoria": "Feminino",
    "ftp_final": null,
    "ftp_final_s": null,
    "montanha": null,
    "montanha_s": null,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": null,
    "tempo_total_s": null,
    "provas": 0,
    "completo": false,
    "pontos_montanha": 0,
    "pontos_cr10k": 0,
    "pontos_ld30k": 0,
    "pontos_total": 0,
    "pos_montanha": null,
    "pos_cr10k": null,
    "pos_ld30k": null,
    "pos_geral": null
  },
  {
    "atleta": "Lívia Revoredo",
    "academia": "BT NS",
    "equipe": "PRO FEMININO",
    "categoria": "Feminino",
    "ftp_final": null,
    "ftp_final_s": null,
    "montanha": null,
    "montanha_s": null,
    "cr10k": "00:26:47",
    "cr10k_s": 1607,
    "ld30k": "00:49:22",
    "ld30k_s": 2962,
    "tempo_total": "01:16:09",
    "tempo_total_s": 4569,
    "provas": 2,
    "completo": false,
    "pontos_montanha": 0,
    "pontos_cr10k": 25,
    "pontos_ld30k": 25,
    "pontos_total": 50,
    "pos_montanha": null,
    "pos_cr10k": 1,
    "pos_ld30k": 1,
    "pos_geral": null
  },
  {
    "atleta": "Bruno Vinicius",
    "academia": "BT TIROL",
    "equipe": "PRO MASCULINO",
    "categoria": "Masculino",
    "ftp_final": null,
    "ftp_final_s": null,
    "montanha": null,
    "montanha_s": null,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": null,
    "tempo_total_s": null,
    "provas": 0,
    "completo": false,
    "pontos_montanha": 0,
    "pontos_cr10k": 0,
    "pontos_ld30k": 0,
    "pontos_total": 0,
    "pos_montanha": null,
    "pos_cr10k": null,
    "pos_ld30k": null,
    "pos_geral": null
  },
  {
    "atleta": "César Britto",
    "academia": "AABB",
    "equipe": "MASTER",
    "categoria": "Masculino",
    "ftp_final": null,
    "ftp_final_s": null,
    "montanha": null,
    "montanha_s": null,
    "cr10k": "00:25:20",
    "cr10k_s": 1520,
    "ld30k": "00:47:06",
    "ld30k_s": 2826,
    "tempo_total": "01:12:26",
    "tempo_total_s": 4346,
    "provas": 2,
    "completo": false,
    "pontos_montanha": 0,
    "pontos_cr10k": 15,
    "pontos_ld30k": 17,
    "pontos_total": 32,
    "pos_montanha": null,
    "pos_cr10k": 4,
    "pos_ld30k": 3,
    "pos_geral": null
  },
  {
    "atleta": "Daniel Azevedo",
    "academia": "BT NS",
    "equipe": "ELITE MASCULINO",
    "categoria": "Masculino",
    "ftp_final": null,
    "ftp_final_s": null,
    "montanha": null,
    "montanha_s": null,
    "cr10k": "00:25:42",
    "cr10k_s": 1542,
    "ld30k": "00:44:27",
    "ld30k_s": 2667,
    "tempo_total": "01:10:09",
    "tempo_total_s": 4209,
    "provas": 2,
    "completo": false,
    "pontos_montanha": 0,
    "pontos_cr10k": 15,
    "pontos_ld30k": 20,
    "pontos_total": 35,
    "pos_montanha": null,
    "pos_cr10k": 4,
    "pos_ld30k": 2,
    "pos_geral": null
  },
  {
    "atleta": "Daniel Freire",
    "academia": "PULSE",
    "equipe": "MASTER",
    "categoria": "Masculino",
    "ftp_final": null,
    "ftp_final_s": null,
    "montanha": null,
    "montanha_s": null,
    "cr10k": "00:25:09",
    "cr10k_s": 1509,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": "00:25:09",
    "tempo_total_s": 1509,
    "provas": 1,
    "completo": false,
    "pontos_montanha": 0,
    "pontos_cr10k": 20,
    "pontos_ld30k": 0,
    "pontos_total": 20,
    "pos_montanha": null,
    "pos_cr10k": 2,
    "pos_ld30k": null,
    "pos_geral": null
  },
  {
    "atleta": "Lydia Tinôco",
    "academia": "AABB",
    "equipe": "ELITE FEMININO",
    "categoria": "Feminino",
    "ftp_final": null,
    "ftp_final_s": null,
    "montanha": null,
    "montanha_s": null,
    "cr10k": "00:28:16",
    "cr10k_s": 1696,
    "ld30k": "00:53:31",
    "ld30k_s": 3211,
    "tempo_total": "01:21:47",
    "tempo_total_s": 4907,
    "provas": 2,
    "completo": false,
    "pontos_montanha": 0,
    "pontos_cr10k": 17,
    "pontos_ld30k": 17,
    "pontos_total": 34,
    "pos_montanha": null,
    "pos_cr10k": 3,
    "pos_ld30k": 3,
    "pos_geral": null
  },
  {
    "atleta": "Elistenio Filho",
    "academia": "BT TIROL",
    "equipe": "SUB-26",
    "categoria": "Masculino",
    "ftp_final": null,
    "ftp_final_s": null,
    "montanha": null,
    "montanha_s": null,
    "cr10k": "00:30:06",
    "cr10k_s": 1806,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": "00:30:06",
    "tempo_total_s": 1806,
    "provas": 1,
    "completo": false,
    "pontos_montanha": 0,
    "pontos_cr10k": 13,
    "pontos_ld30k": 0,
    "pontos_total": 13,
    "pos_montanha": null,
    "pos_cr10k": 5,
    "pos_ld30k": null,
    "pos_geral": null
  },
  {
    "atleta": "Francisco Vito",
    "academia": "PULSE",
    "equipe": "SUB-26",
    "categoria": "Masculino",
    "ftp_final": null,
    "ftp_final_s": null,
    "montanha": null,
    "montanha_s": null,
    "cr10k": "00:26:53",
    "cr10k_s": 1613,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": "00:26:53",
    "tempo_total_s": 1613,
    "provas": 1,
    "completo": false,
    "pontos_montanha": 0,
    "pontos_cr10k": 20,
    "pontos_ld30k": 0,
    "pontos_total": 20,
    "pos_montanha": null,
    "pos_cr10k": 2,
    "pos_ld30k": null,
    "pos_geral": null
  },
  {
    "atleta": "Haroldo Duarte",
    "academia": "AABB",
    "equipe": "PRO MASCULINO",
    "categoria": "Masculino",
    "ftp_final": null,
    "ftp_final_s": null,
    "montanha": null,
    "montanha_s": null,
    "cr10k": "00:25:11",
    "cr10k_s": 1511,
    "ld30k": "00:47:58",
    "ld30k_s": 2878,
    "tempo_total": "01:13:09",
    "tempo_total_s": 4389,
    "provas": 2,
    "completo": false,
    "pontos_montanha": 0,
    "pontos_cr10k": 25,
    "pontos_ld30k": 17,
    "pontos_total": 42,
    "pos_montanha": null,
    "pos_cr10k": 1,
    "pos_ld30k": 3,
    "pos_geral": null
  },
  {
    "atleta": "Igor Rosado",
    "academia": "BT TIROL",
    "equipe": "PRO MASCULINO",
    "categoria": "Masculino",
    "ftp_final": null,
    "ftp_final_s": null,
    "montanha": null,
    "montanha_s": null,
    "cr10k": "00:28:19",
    "cr10k_s": 1699,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": "00:28:19",
    "tempo_total_s": 1699,
    "provas": 1,
    "completo": false,
    "pontos_montanha": 0,
    "pontos_cr10k": 17,
    "pontos_ld30k": 0,
    "pontos_total": 17,
    "pos_montanha": null,
    "pos_cr10k": 3,
    "pos_ld30k": null,
    "pos_geral": null
  },
  {
    "atleta": "Raissa Georgia",
    "academia": "BT TIROL",
    "equipe": "ELITE FEMININO",
    "categoria": "Feminino",
    "ftp_final": null,
    "ftp_final_s": null,
    "montanha": null,
    "montanha_s": null,
    "cr10k": "00:26:57",
    "cr10k_s": 1617,
    "ld30k": "00:50:44",
    "ld30k_s": 3044,
    "tempo_total": "01:17:41",
    "tempo_total_s": 4661,
    "provas": 2,
    "completo": false,
    "pontos_montanha": 0,
    "pontos_cr10k": 20,
    "pontos_ld30k": 20,
    "pontos_total": 40,
    "pos_montanha": null,
    "pos_cr10k": 2,
    "pos_ld30k": 2,
    "pos_geral": null
  },
  {
    "atleta": "Jair",
    "academia": "BT NS",
    "equipe": "PRO MASCULINO",
    "categoria": "Masculino",
    "ftp_final": null,
    "ftp_final_s": null,
    "montanha": null,
    "montanha_s": null,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": null,
    "tempo_total_s": null,
    "provas": 0,
    "completo": false,
    "pontos_montanha": 0,
    "pontos_cr10k": 0,
    "pontos_ld30k": 0,
    "pontos_total": 0,
    "pos_montanha": null,
    "pos_cr10k": null,
    "pos_ld30k": null,
    "pos_geral": null
  },
  {
    "atleta": "Joao Pedro",
    "academia": "BT NS",
    "equipe": "SUB-26",
    "categoria": "Masculino",
    "ftp_final": null,
    "ftp_final_s": null,
    "montanha": null,
    "montanha_s": null,
    "cr10k": "00:25:02",
    "cr10k_s": 1502,
    "ld30k": "00:45:06",
    "ld30k_s": 2706,
    "tempo_total": "01:10:08",
    "tempo_total_s": 4208,
    "provas": 2,
    "completo": false,
    "pontos_montanha": 0,
    "pontos_cr10k": 25,
    "pontos_ld30k": 25,
    "pontos_total": 50,
    "pos_montanha": null,
    "pos_cr10k": 1,
    "pos_ld30k": 1,
    "pos_geral": null
  },
  {
    "atleta": "Samara Silva",
    "academia": "BT NS",
    "equipe": "SUB-26",
    "categoria": "Feminino",
    "ftp_final": null,
    "ftp_final_s": null,
    "montanha": null,
    "montanha_s": null,
    "cr10k": "00:30:54",
    "cr10k_s": 1854,
    "ld30k": "01:00:28",
    "ld30k_s": 3628,
    "tempo_total": "01:31:22",
    "tempo_total_s": 5482,
    "provas": 2,
    "completo": false,
    "pontos_montanha": 0,
    "pontos_cr10k": 11,
    "pontos_ld30k": 9,
    "pontos_total": 20,
    "pos_montanha": null,
    "pos_cr10k": 6,
    "pos_ld30k": 7,
    "pos_geral": null
  },
  {
    "atleta": "Sheila Sales",
    "academia": "AABB",
    "equipe": "MASTER",
    "categoria": "Feminino",
    "ftp_final": null,
    "ftp_final_s": null,
    "montanha": null,
    "montanha_s": null,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:55:38",
    "ld30k_s": 3338,
    "tempo_total": "00:55:38",
    "tempo_total_s": 3338,
    "provas": 1,
    "completo": false,
    "pontos_montanha": 0,
    "pontos_cr10k": 0,
    "pontos_ld30k": 3,
    "pontos_total": 3,
    "pos_montanha": null,
    "pos_cr10k": null,
    "pos_ld30k": 10,
    "pos_geral": null
  },
  {
    "atleta": "Maria J nobrega",
    "academia": "BT TIROL",
    "equipe": "SUB-26",
    "categoria": "Feminino",
    "ftp_final": "00:00:00",
    "ftp_final_s": 0,
    "montanha": null,
    "montanha_s": null,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:49:01",
    "ld30k_s": 2941,
    "tempo_total": "00:49:01",
    "tempo_total_s": 2941,
    "provas": 2,
    "completo": false,
    "pontos_montanha": 0,
    "pontos_cr10k": 0,
    "pontos_ld30k": 17,
    "pontos_total": 17,
    "pos_montanha": null,
    "pos_cr10k": null,
    "pos_ld30k": 3,
    "pos_geral": null
  },
  {
    "atleta": "CLAUDIA REGINA",
    "academia": "BT TIROL",
    "equipe": "MASTER",
    "categoria": "Feminino",
    "ftp_final": "00:00:16",
    "ftp_final_s": 16,
    "montanha": null,
    "montanha_s": null,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:53:31",
    "ld30k_s": 3211,
    "tempo_total": "00:53:47",
    "tempo_total_s": 3227,
    "provas": 2,
    "completo": false,
    "pontos_montanha": 0,
    "pontos_cr10k": 0,
    "pontos_ld30k": 7,
    "pontos_total": 7,
    "pos_montanha": null,
    "pos_cr10k": null,
    "pos_ld30k": 8,
    "pos_geral": null
  },
  {
    "atleta": "Simone Ribeiro",
    "academia": "BT NS",
    "equipe": "ELITE FEMININO",
    "categoria": "Feminino",
    "ftp_final": "00:00:04",
    "ftp_final_s": 4,
    "montanha": "00:26:23",
    "montanha_s": 1583,
    "cr10k": "00:48:05",
    "cr10k_s": 2885,
    "ld30k": "01:14:32",
    "ld30k_s": 4472,
    "tempo_total": "01:14:32",
    "tempo_total_s": 4472,
    "provas": 3,
    "completo": true,
    "pontos_montanha": 17,
    "pontos_cr10k": 13,
    "pontos_ld30k": 15,
    "pontos_total": 45,
    "pos_montanha": 3,
    "pos_cr10k": 5,
    "pos_ld30k": 4,
    "pos_geral": 1,
    "pos_geral_categoria": 1
  },
  {
    "atleta": "Kleber Gentil",
    "academia": "BT NS",
    "equipe": "PRO MASCULINO",
    "categoria": "Masculino",
    "ftp_final": null,
    "ftp_final_s": null,
    "montanha": null,
    "montanha_s": null,
    "cr10k": "00:26:13",
    "cr10k_s": 1573,
    "ld30k": "00:53:13",
    "ld30k_s": 3193,
    "tempo_total": "01:19:26",
    "tempo_total_s": 4766,
    "provas": 2,
    "completo": false,
    "pontos_montanha": 0,
    "pontos_cr10k": 20,
    "pontos_ld30k": 13,
    "pontos_total": 33,
    "pos_montanha": null,
    "pos_cr10k": 2,
    "pos_ld30k": 5,
    "pos_geral": null
  },
  {
    "atleta": "Luiz Marcelo",
    "academia": "PULSE",
    "equipe": "PRO MASCULINO",
    "categoria": "Masculino",
    "ftp_final": null,
    "ftp_final_s": null,
    "montanha": null,
    "montanha_s": null,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:48:29",
    "ld30k_s": 2909,
    "tempo_total": "00:48:29",
    "tempo_total_s": 2909,
    "provas": 1,
    "completo": false,
    "pontos_montanha": 0,
    "pontos_cr10k": 0,
    "pontos_ld30k": 15,
    "pontos_total": 15,
    "pos_montanha": null,
    "pos_cr10k": null,
    "pos_ld30k": 4,
    "pos_geral": null
  },
  {
    "atleta": "Rafael Povoas",
    "academia": "PULSE",
    "equipe": "ELITE MASCULINO",
    "categoria": "Masculino",
    "ftp_final": null,
    "ftp_final_s": null,
    "montanha": null,
    "montanha_s": null,
    "cr10k": "00:24:43",
    "cr10k_s": 1483,
    "ld30k": "00:45:56",
    "ld30k_s": 2756,
    "tempo_total": "01:10:39",
    "tempo_total_s": 4239,
    "provas": 2,
    "completo": false,
    "pontos_montanha": 0,
    "pontos_cr10k": 17,
    "pontos_ld30k": 15,
    "pontos_total": 32,
    "pos_montanha": null,
    "pos_cr10k": 3,
    "pos_ld30k": 4,
    "pos_geral": null
  },
  {
    "atleta": "Sivonaldo Tercio",
    "academia": "AABB",
    "equipe": "ELITE MASCULINO",
    "categoria": "Masculino",
    "ftp_final": null,
    "ftp_final_s": null,
    "montanha": null,
    "montanha_s": null,
    "cr10k": "00:22:30",
    "cr10k_s": 1350,
    "ld30k": "00:42:34",
    "ld30k_s": 2554,
    "tempo_total": "01:05:04",
    "tempo_total_s": 3904,
    "provas": 2,
    "completo": false,
    "pontos_montanha": 0,
    "pontos_cr10k": 25,
    "pontos_ld30k": 25,
    "pontos_total": 50,
    "pos_montanha": null,
    "pos_cr10k": 1,
    "pos_ld30k": 1,
    "pos_geral": null
  },
  {
    "atleta": "Omar Dantas",
    "academia": "BT NS",
    "equipe": "ELITE MASCULINO",
    "categoria": "Masculino",
    "ftp_final": "00:00:13",
    "ftp_final_s": 13,
    "montanha": "00:22:45",
    "montanha_s": 1365,
    "cr10k": "00:41:42",
    "cr10k_s": 2502,
    "ld30k": "01:04:40",
    "ld30k_s": 3880,
    "tempo_total": "01:04:40",
    "tempo_total_s": 3880,
    "provas": 3,
    "completo": true,
    "pontos_montanha": 25,
    "pontos_cr10k": 13,
    "pontos_ld30k": 11,
    "pontos_total": 49,
    "pos_montanha": 1,
    "pos_cr10k": 5,
    "pos_ld30k": 6,
    "pos_geral": 1,
    "pos_geral_categoria": 1
  },
  {
    "atleta": "Sergio Torralba",
    "academia": "BT TIROL",
    "equipe": "ELITE MASCULINO",
    "categoria": "Masculino",
    "ftp_final": "00:00:03",
    "ftp_final_s": 3,
    "montanha": "00:23:04",
    "montanha_s": 1384,
    "cr10k": "00:41:55",
    "cr10k_s": 2515,
    "ld30k": "01:05:02",
    "ld30k_s": 3902,
    "tempo_total": "01:05:02",
    "tempo_total_s": 3902,
    "provas": 3,
    "completo": true,
    "pontos_montanha": 17,
    "pontos_cr10k": 11,
    "pontos_ld30k": 9,
    "pontos_total": 37,
    "pos_montanha": 3,
    "pos_cr10k": 6,
    "pos_ld30k": 7,
    "pos_geral": 2,
    "pos_geral_categoria": 2
  },
  {
    "atleta": "Diogo Almeida",
    "academia": "PULSE",
    "equipe": "ELITE MASCULINO",
    "categoria": "Masculino",
    "ftp_final": "00:00:05",
    "ftp_final_s": 5,
    "montanha": "00:24:09",
    "montanha_s": 1449,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": "00:24:14",
    "tempo_total_s": 1454,
    "provas": 2,
    "completo": false,
    "pontos_montanha": 9,
    "pontos_cr10k": 0,
    "pontos_ld30k": 0,
    "pontos_total": 9,
    "pos_montanha": 7,
    "pos_cr10k": null,
    "pos_ld30k": null,
    "pos_geral": null
  },
  {
    "atleta": "Bruno Cabral",
    "academia": "AABB",
    "equipe": "PRO MASCULINO",
    "categoria": "Masculino",
    "ftp_final": "00:00:09",
    "ftp_final_s": 9,
    "montanha": "00:24:33",
    "montanha_s": 1473,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": "00:24:42",
    "tempo_total_s": 1482,
    "provas": 2,
    "completo": false,
    "pontos_montanha": 25,
    "pontos_cr10k": 0,
    "pontos_ld30k": 0,
    "pontos_total": 25,
    "pos_montanha": 1,
    "pos_cr10k": null,
    "pos_ld30k": null,
    "pos_geral": null
  },
  {
    "atleta": "Arthur Dantas",
    "academia": "PULSE",
    "equipe": "PRO MASCULINO",
    "categoria": "Masculino",
    "ftp_final": "00:00:10",
    "ftp_final_s": 10,
    "montanha": "00:24:42",
    "montanha_s": 1482,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": "00:24:52",
    "tempo_total_s": 1492,
    "provas": 2,
    "completo": false,
    "pontos_montanha": 20,
    "pontos_cr10k": 0,
    "pontos_ld30k": 0,
    "pontos_total": 20,
    "pos_montanha": 2,
    "pos_cr10k": null,
    "pos_ld30k": null,
    "pos_geral": null
  },
  {
    "atleta": "Carlos Thompson",
    "academia": "BT TIROL",
    "equipe": "PRO MASCULINO",
    "categoria": "Masculino",
    "ftp_final": "00:00:10",
    "ftp_final_s": 10,
    "montanha": "00:26:00",
    "montanha_s": 1560,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": "00:26:10",
    "tempo_total_s": 1570,
    "provas": 2,
    "completo": false,
    "pontos_montanha": 9,
    "pontos_cr10k": 0,
    "pontos_ld30k": 0,
    "pontos_total": 9,
    "pos_montanha": 7,
    "pos_cr10k": null,
    "pos_ld30k": null,
    "pos_geral": null
  },
  {
    "atleta": "Heloisa Lopes",
    "academia": "BT TIROL",
    "equipe": "PRO FEMININO",
    "categoria": "Feminino",
    "ftp_final": "00:00:09",
    "ftp_final_s": 9,
    "montanha": null,
    "montanha_s": null,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:53:42",
    "ld30k_s": 3222,
    "tempo_total": "00:53:51",
    "tempo_total_s": 3231,
    "provas": 2,
    "completo": false,
    "pontos_montanha": 0,
    "pontos_cr10k": 0,
    "pontos_ld30k": 20,
    "pontos_total": 20,
    "pos_montanha": null,
    "pos_cr10k": null,
    "pos_ld30k": 2,
    "pos_geral": null
  },
  {
    "atleta": "LIEGE",
    "academia": "PULSE",
    "equipe": "MASTER",
    "categoria": "Feminino",
    "ftp_final": "00:00:09",
    "ftp_final_s": 9,
    "montanha": null,
    "montanha_s": null,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:50:14",
    "ld30k_s": 3014,
    "tempo_total": "00:50:23",
    "tempo_total_s": 3023,
    "provas": 2,
    "completo": false,
    "pontos_montanha": 0,
    "pontos_cr10k": 0,
    "pontos_ld30k": 11,
    "pontos_total": 11,
    "pos_montanha": null,
    "pos_cr10k": null,
    "pos_ld30k": 6,
    "pos_geral": null
  },
  {
    "atleta": "Lucas Leonardo",
    "academia": "PULSE",
    "equipe": "ELITE MASCULINO",
    "categoria": "Masculino",
    "ftp_final": "00:00:12",
    "ftp_final_s": 12,
    "montanha": "00:22:47",
    "montanha_s": 1367,
    "cr10k": "00:42:57",
    "cr10k_s": 2577,
    "ld30k": "01:05:56",
    "ld30k_s": 3956,
    "tempo_total": "01:05:56",
    "tempo_total_s": 3956,
    "provas": 3,
    "completo": true,
    "pontos_montanha": 20,
    "pontos_cr10k": 9,
    "pontos_ld30k": 7,
    "pontos_total": 36,
    "pos_montanha": 2,
    "pos_cr10k": 7,
    "pos_ld30k": 8,
    "pos_geral": 3,
    "pos_geral_categoria": 3
  },
  {
    "atleta": "Andréia Medeiros",
    "academia": "BT TIROL",
    "equipe": "ELITE FEMININO",
    "categoria": "Feminino",
    "ftp_final": "00:00:11",
    "ftp_final_s": 11,
    "montanha": "00:26:19",
    "montanha_s": 1579,
    "cr10k": "00:48:16",
    "cr10k_s": 2896,
    "ld30k": "01:14:46",
    "ld30k_s": 4486,
    "tempo_total": "01:14:46",
    "tempo_total_s": 4486,
    "provas": 3,
    "completo": true,
    "pontos_montanha": 20,
    "pontos_cr10k": 11,
    "pontos_ld30k": 13,
    "pontos_total": 44,
    "pos_montanha": 2,
    "pos_cr10k": 6,
    "pos_ld30k": 5,
    "pos_geral": 2,
    "pos_geral_categoria": 2
  },
  {
    "atleta": "Neto Xavier",
    "academia": "BT NS",
    "equipe": "ELITE MASCULINO",
    "categoria": "Masculino",
    "ftp_final": "00:00:00",
    "ftp_final_s": 0,
    "montanha": "00:23:38",
    "montanha_s": 1418,
    "cr10k": "00:44:32",
    "cr10k_s": 2672,
    "ld30k": "01:08:10",
    "ld30k_s": 4090,
    "tempo_total": "01:08:10",
    "tempo_total_s": 4090,
    "provas": 3,
    "completo": true,
    "pontos_montanha": 13,
    "pontos_cr10k": 5,
    "pontos_ld30k": 5,
    "pontos_total": 23,
    "pos_montanha": 5,
    "pos_cr10k": 9,
    "pos_ld30k": 9,
    "pos_geral": 4,
    "pos_geral_categoria": 4
  },
  {
    "atleta": "Alini Brito",
    "academia": "BT NS",
    "equipe": "ELITE FEMININO",
    "categoria": "Feminino",
    "ftp_final": "00:00:10",
    "ftp_final_s": 10,
    "montanha": "00:26:18",
    "montanha_s": 1578,
    "cr10k": "00:48:31",
    "cr10k_s": 2911,
    "ld30k": "01:14:59",
    "ld30k_s": 4499,
    "tempo_total": "01:14:59",
    "tempo_total_s": 4499,
    "provas": 3,
    "completo": true,
    "pontos_montanha": 25,
    "pontos_cr10k": 9,
    "pontos_ld30k": 11,
    "pontos_total": 45,
    "pos_montanha": 1,
    "pos_cr10k": 7,
    "pos_ld30k": 6,
    "pos_geral": 3,
    "pos_geral_categoria": 3
  },
  {
    "atleta": "Joyce Ribeiro",
    "academia": "BT NS",
    "equipe": "ELITE FEMININO",
    "categoria": "Feminino",
    "ftp_final": "00:00:11",
    "ftp_final_s": 11,
    "montanha": "00:26:54",
    "montanha_s": 1614,
    "cr10k": "00:48:01",
    "cr10k_s": 2881,
    "ld30k": "01:15:06",
    "ld30k_s": 4506,
    "tempo_total": "01:15:06",
    "tempo_total_s": 4506,
    "provas": 3,
    "completo": true,
    "pontos_montanha": 13,
    "pontos_cr10k": 15,
    "pontos_ld30k": 9,
    "pontos_total": 37,
    "pos_montanha": 5,
    "pos_cr10k": 4,
    "pos_ld30k": 7,
    "pos_geral": 4,
    "pos_geral_categoria": 4
  },
  {
    "atleta": "Renata Seixas",
    "academia": "BT TIROL",
    "equipe": "ELITE FEMININO",
    "categoria": "Feminino",
    "ftp_final": "00:00:17",
    "ftp_final_s": 17,
    "montanha": "00:26:45",
    "montanha_s": 1605,
    "cr10k": "00:49:42",
    "cr10k_s": 2982,
    "ld30k": "01:16:44",
    "ld30k_s": 4604,
    "tempo_total": "01:16:44",
    "tempo_total_s": 4604,
    "provas": 3,
    "completo": true,
    "pontos_montanha": 15,
    "pontos_cr10k": 5,
    "pontos_ld30k": 7,
    "pontos_total": 27,
    "pos_montanha": 4,
    "pos_cr10k": 9,
    "pos_ld30k": 8,
    "pos_geral": 5,
    "pos_geral_categoria": 5
  },
  {
    "atleta": "Bira Carratu",
    "academia": "AABB",
    "equipe": "ELITE MASCULINO",
    "categoria": "Masculino",
    "ftp_final": "00:00:11",
    "ftp_final_s": 11,
    "montanha": "00:23:39",
    "montanha_s": 1419,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": "00:23:50",
    "tempo_total_s": 1430,
    "provas": 2,
    "completo": false,
    "pontos_montanha": 11,
    "pontos_cr10k": 0,
    "pontos_ld30k": 0,
    "pontos_total": 11,
    "pos_montanha": 6,
    "pos_cr10k": null,
    "pos_ld30k": null,
    "pos_geral": null
  },
  {
    "atleta": "Raimundo Romão",
    "academia": "BT NS",
    "equipe": "MASTER",
    "categoria": "Masculino",
    "ftp_final": "00:00:11",
    "ftp_final_s": 11,
    "montanha": null,
    "montanha_s": null,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:43:44",
    "ld30k_s": 2624,
    "tempo_total": "00:43:55",
    "tempo_total_s": 2635,
    "provas": 2,
    "completo": false,
    "pontos_montanha": 0,
    "pontos_cr10k": 0,
    "pontos_ld30k": 25,
    "pontos_total": 25,
    "pos_montanha": null,
    "pos_cr10k": null,
    "pos_ld30k": 1,
    "pos_geral": null
  },
  {
    "atleta": "Jannaina Queiroz",
    "academia": "BT TIROL",
    "equipe": "ELITE FEMININO",
    "categoria": "Feminino",
    "ftp_final": "00:00:11",
    "ftp_final_s": 11,
    "montanha": null,
    "montanha_s": null,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": "00:00:11",
    "tempo_total_s": 11,
    "provas": 1,
    "completo": false,
    "pontos_montanha": 0,
    "pontos_cr10k": 0,
    "pontos_ld30k": 0,
    "pontos_total": 0,
    "pos_montanha": null,
    "pos_cr10k": null,
    "pos_ld30k": null,
    "pos_geral": null
  },
  {
    "atleta": "Silvia Drummond",
    "academia": "AABB",
    "equipe": "ELITE FEMININO",
    "categoria": "Feminino",
    "ftp_final": "00:00:11",
    "ftp_final_s": 11,
    "montanha": "00:27:54",
    "montanha_s": 1674,
    "cr10k": "00:48:55",
    "cr10k_s": 2935,
    "ld30k": "01:17:00",
    "ld30k_s": 4620,
    "tempo_total": "01:17:00",
    "tempo_total_s": 4620,
    "provas": 3,
    "completo": true,
    "pontos_montanha": 9,
    "pontos_cr10k": 7,
    "pontos_ld30k": 5,
    "pontos_total": 21,
    "pos_montanha": 7,
    "pos_cr10k": 8,
    "pos_ld30k": 9,
    "pos_geral": 6,
    "pos_geral_categoria": 6
  },
  {
    "atleta": "Sarah Brito",
    "academia": "AABB",
    "equipe": "ELITE FEMININO",
    "categoria": "Feminino",
    "ftp_final": "00:00:09",
    "ftp_final_s": 9,
    "montanha": "00:27:10",
    "montanha_s": 1630,
    "cr10k": "00:49:48",
    "cr10k_s": 2988,
    "ld30k": "01:17:07",
    "ld30k_s": 4627,
    "tempo_total": "01:17:07",
    "tempo_total_s": 4627,
    "provas": 3,
    "completo": true,
    "pontos_montanha": 11,
    "pontos_cr10k": 3,
    "pontos_ld30k": 3,
    "pontos_total": 17,
    "pos_montanha": 6,
    "pos_cr10k": 10,
    "pos_ld30k": 10,
    "pos_geral": 7,
    "pos_geral_categoria": 7
  },
  {
    "atleta": "Renato Araújo",
    "academia": "AABB",
    "equipe": "ELITE MASCULINO",
    "categoria": "Masculino",
    "ftp_final": "00:00:11",
    "ftp_final_s": 11,
    "montanha": null,
    "montanha_s": null,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:48:12",
    "ld30k_s": 2892,
    "tempo_total": "00:48:23",
    "tempo_total_s": 2903,
    "provas": 2,
    "completo": false,
    "pontos_montanha": 0,
    "pontos_cr10k": 0,
    "pontos_ld30k": 13,
    "pontos_total": 13,
    "pos_montanha": null,
    "pos_cr10k": null,
    "pos_ld30k": 5,
    "pos_geral": null
  },
  {
    "atleta": "Andreia Araujo",
    "academia": "BT TIROL",
    "equipe": "PRO FEMININO",
    "categoria": "Feminino",
    "ftp_final": "00:00:21",
    "ftp_final_s": 21,
    "montanha": "00:27:33",
    "montanha_s": 1653,
    "cr10k": "00:52:24",
    "cr10k_s": 3144,
    "ld30k": "01:20:18",
    "ld30k_s": 4818,
    "tempo_total": "01:20:18",
    "tempo_total_s": 4818,
    "provas": 3,
    "completo": true,
    "pontos_montanha": 25,
    "pontos_cr10k": 17,
    "pontos_ld30k": 13,
    "pontos_total": 55,
    "pos_montanha": 1,
    "pos_cr10k": 3,
    "pos_ld30k": 5,
    "pos_geral": 8,
    "pos_geral_categoria": 1
  },
  {
    "atleta": "Hívila Moreira",
    "academia": "PULSE",
    "equipe": "ELITE FEMININO",
    "categoria": "Feminino",
    "ftp_final": "00:00:14",
    "ftp_final_s": 14,
    "montanha": "00:28:02",
    "montanha_s": 1682,
    "cr10k": "00:52:39",
    "cr10k_s": 3159,
    "ld30k": "01:20:55",
    "ld30k_s": 4855,
    "tempo_total": "01:20:55",
    "tempo_total_s": 4855,
    "provas": 3,
    "completo": true,
    "pontos_montanha": 7,
    "pontos_cr10k": 0,
    "pontos_ld30k": 1,
    "pontos_total": 8,
    "pos_montanha": 8,
    "pos_cr10k": 12,
    "pos_ld30k": 11,
    "pos_geral": 9,
    "pos_geral_categoria": 8
  },
  {
    "atleta": "Genival Ferreira",
    "academia": "AABB",
    "equipe": "ELITE MASCULINO",
    "categoria": "Masculino",
    "ftp_final": "00:00:11",
    "ftp_final_s": 11,
    "montanha": "00:23:37",
    "montanha_s": 1417,
    "cr10k": "00:44:28",
    "cr10k_s": 2668,
    "ld30k": "01:08:16",
    "ld30k_s": 4096,
    "tempo_total": "01:08:16",
    "tempo_total_s": 4096,
    "provas": 3,
    "completo": true,
    "pontos_montanha": 15,
    "pontos_cr10k": 7,
    "pontos_ld30k": 3,
    "pontos_total": 25,
    "pos_montanha": 4,
    "pos_cr10k": 8,
    "pos_ld30k": 10,
    "pos_geral": 5,
    "pos_geral_categoria": 5
  },
  {
    "atleta": "Karine Symonir",
    "academia": "PULSE",
    "equipe": "ELITE FEMININO",
    "categoria": "Feminino",
    "ftp_final": "00:00:15",
    "ftp_final_s": 15,
    "montanha": "00:28:17",
    "montanha_s": 1697,
    "cr10k": "00:52:25",
    "cr10k_s": 3145,
    "ld30k": "01:20:57",
    "ld30k_s": 4857,
    "tempo_total": "01:20:57",
    "tempo_total_s": 4857,
    "provas": 3,
    "completo": true,
    "pontos_montanha": 5,
    "pontos_cr10k": 1,
    "pontos_ld30k": 0,
    "pontos_total": 6,
    "pos_montanha": 9,
    "pos_cr10k": 11,
    "pos_ld30k": 12,
    "pos_geral": 10,
    "pos_geral_categoria": 9
  },
  {
    "atleta": "Lucas Eurípides",
    "academia": "BT TIROL",
    "equipe": "SUB-26",
    "categoria": "Masculino",
    "ftp_final": "00:00:17",
    "ftp_final_s": 17,
    "montanha": "00:25:02",
    "montanha_s": 1502,
    "cr10k": "00:44:37",
    "cr10k_s": 2677,
    "ld30k": "01:09:56",
    "ld30k_s": 4196,
    "tempo_total": "01:09:56",
    "tempo_total_s": 4196,
    "provas": 3,
    "completo": true,
    "pontos_montanha": 25,
    "pontos_cr10k": 9,
    "pontos_ld30k": 5,
    "pontos_total": 39,
    "pos_montanha": 1,
    "pos_cr10k": 7,
    "pos_ld30k": 9,
    "pos_geral": 6,
    "pos_geral_categoria": 1
  },
  {
    "atleta": "Gringo",
    "academia": "BT NS",
    "equipe": "ELITE MASCULINO",
    "categoria": "Masculino",
    "ftp_final": "00:00:13",
    "ftp_final_s": 13,
    "montanha": "00:25:14",
    "montanha_s": 1514,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": "00:25:27",
    "tempo_total_s": 1527,
    "provas": 2,
    "completo": false,
    "pontos_montanha": 5,
    "pontos_cr10k": 0,
    "pontos_ld30k": 0,
    "pontos_total": 5,
    "pos_montanha": 9,
    "pos_cr10k": null,
    "pos_ld30k": null,
    "pos_geral": null
  },
  {
    "atleta": "José Wilson",
    "academia": "PULSE",
    "equipe": "SUB-26",
    "categoria": "Masculino",
    "ftp_final": "00:00:13",
    "ftp_final_s": 13,
    "montanha": null,
    "montanha_s": null,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:46:42",
    "ld30k_s": 2802,
    "tempo_total": "00:46:55",
    "tempo_total_s": 2815,
    "provas": 2,
    "completo": false,
    "pontos_montanha": 0,
    "pontos_cr10k": 0,
    "pontos_ld30k": 20,
    "pontos_total": 20,
    "pos_montanha": null,
    "pos_cr10k": null,
    "pos_ld30k": 2,
    "pos_geral": null
  },
  {
    "atleta": "Olisuel Pereira",
    "academia": "PULSE",
    "equipe": "PRO MASCULINO",
    "categoria": "Masculino",
    "ftp_final": "00:00:14",
    "ftp_final_s": 14,
    "montanha": "00:24:49",
    "montanha_s": 1489,
    "cr10k": "00:45:24",
    "cr10k_s": 2724,
    "ld30k": "01:10:27",
    "ld30k_s": 4227,
    "tempo_total": "01:10:27",
    "tempo_total_s": 4227,
    "provas": 3,
    "completo": true,
    "pontos_montanha": 13,
    "pontos_cr10k": 15,
    "pontos_ld30k": 11,
    "pontos_total": 39,
    "pos_montanha": 5,
    "pos_cr10k": 4,
    "pos_ld30k": 6,
    "pos_geral": 7,
    "pos_geral_categoria": 1
  },
  {
    "atleta": "Livia Darc",
    "academia": "BT NS",
    "equipe": "SUB-26",
    "categoria": "Feminino",
    "ftp_final": "00:00:15",
    "ftp_final_s": 15,
    "montanha": "00:29:19",
    "montanha_s": 1759,
    "cr10k": "00:51:51",
    "cr10k_s": 3111,
    "ld30k": "01:21:25",
    "ld30k_s": 4885,
    "tempo_total": "01:21:25",
    "tempo_total_s": 4885,
    "provas": 3,
    "completo": true,
    "pontos_montanha": 9,
    "pontos_cr10k": 3,
    "pontos_ld30k": 0,
    "pontos_total": 12,
    "pos_montanha": 7,
    "pos_cr10k": 10,
    "pos_ld30k": 12,
    "pos_geral": 11,
    "pos_geral_categoria": 4
  },
  {
    "atleta": "Camila Mota",
    "academia": "AABB",
    "equipe": "PRO FEMININO",
    "categoria": "Feminino",
    "ftp_final": "00:00:14",
    "ftp_final_s": 14,
    "montanha": "00:28:39",
    "montanha_s": 1719,
    "cr10k": "00:52:47",
    "cr10k_s": 3167,
    "ld30k": "01:21:40",
    "ld30k_s": 4900,
    "tempo_total": "01:21:40",
    "tempo_total_s": 4900,
    "provas": 3,
    "completo": true,
    "pontos_montanha": 17,
    "pontos_cr10k": 15,
    "pontos_ld30k": 11,
    "pontos_total": 43,
    "pos_montanha": 3,
    "pos_cr10k": 4,
    "pos_ld30k": 6,
    "pos_geral": 12,
    "pos_geral_categoria": 2
  },
  {
    "atleta": "Beatriz Bezerra",
    "academia": "BT NS",
    "equipe": "PRO FEMININO",
    "categoria": "Feminino",
    "ftp_final": "00:00:13",
    "ftp_final_s": 13,
    "montanha": "00:28:49",
    "montanha_s": 1729,
    "cr10k": "00:52:56",
    "cr10k_s": 3176,
    "ld30k": "01:21:58",
    "ld30k_s": 4918,
    "tempo_total": "01:21:58",
    "tempo_total_s": 4918,
    "provas": 3,
    "completo": true,
    "pontos_montanha": 13,
    "pontos_cr10k": 11,
    "pontos_ld30k": 9,
    "pontos_total": 33,
    "pos_montanha": 5,
    "pos_cr10k": 6,
    "pos_ld30k": 7,
    "pos_geral": 13,
    "pos_geral_categoria": 3
  },
  {
    "atleta": "Vanessa Rodrigues",
    "academia": "BT TIROL",
    "equipe": "PRO FEMININO",
    "categoria": "Feminino",
    "ftp_final": "00:00:14",
    "ftp_final_s": 14,
    "montanha": "00:29:36",
    "montanha_s": 1776,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": "00:29:50",
    "tempo_total_s": 1790,
    "provas": 2,
    "completo": false,
    "pontos_montanha": 7,
    "pontos_cr10k": 0,
    "pontos_ld30k": 0,
    "pontos_total": 7,
    "pos_montanha": 8,
    "pos_cr10k": null,
    "pos_ld30k": null,
    "pos_geral": null
  },
  {
    "atleta": "José Arimatéia",
    "academia": "AABB",
    "equipe": "PRO MASCULINO",
    "categoria": "Masculino",
    "ftp_final": "00:00:11",
    "ftp_final_s": 11,
    "montanha": "00:24:46",
    "montanha_s": 1486,
    "cr10k": "00:46:12",
    "cr10k_s": 2772,
    "ld30k": "01:11:09",
    "ld30k_s": 4269,
    "tempo_total": "01:11:09",
    "tempo_total_s": 4269,
    "provas": 3,
    "completo": true,
    "pontos_montanha": 15,
    "pontos_cr10k": 13,
    "pontos_ld30k": 9,
    "pontos_total": 37,
    "pos_montanha": 4,
    "pos_cr10k": 5,
    "pos_ld30k": 7,
    "pos_geral": 8,
    "pos_geral_categoria": 2
  },
  {
    "atleta": "Oona Lopes",
    "academia": "AABB",
    "equipe": "ELITE FEMININO",
    "categoria": "Feminino",
    "ftp_final": "00:00:14",
    "ftp_final_s": 14,
    "montanha": null,
    "montanha_s": null,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": "00:00:14",
    "tempo_total_s": 14,
    "provas": 1,
    "completo": false,
    "pontos_montanha": 0,
    "pontos_cr10k": 0,
    "pontos_ld30k": 0,
    "pontos_total": 0,
    "pos_montanha": null,
    "pos_cr10k": null,
    "pos_ld30k": null,
    "pos_geral": null
  },
  {
    "atleta": "Socorro Linhares",
    "academia": "BT NS",
    "equipe": "MASTER",
    "categoria": "Feminino",
    "ftp_final": "00:00:14",
    "ftp_final_s": 14,
    "montanha": "00:29:17",
    "montanha_s": 1757,
    "cr10k": "00:52:42",
    "cr10k_s": 3162,
    "ld30k": "01:22:13",
    "ld30k_s": 4933,
    "tempo_total": "01:22:13",
    "tempo_total_s": 4933,
    "provas": 3,
    "completo": true,
    "pontos_montanha": 9,
    "pontos_cr10k": 3,
    "pontos_ld30k": 0,
    "pontos_total": 12,
    "pos_montanha": 7,
    "pos_cr10k": 10,
    "pos_ld30k": 13,
    "pos_geral": 14,
    "pos_geral_categoria": 3
  },
  {
    "atleta": "Helena Jales",
    "academia": "AABB",
    "equipe": "PRO FEMININO",
    "categoria": "Feminino",
    "ftp_final": "00:00:14",
    "ftp_final_s": 14,
    "montanha": null,
    "montanha_s": null,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": "00:00:14",
    "tempo_total_s": 14,
    "provas": 1,
    "completo": false,
    "pontos_montanha": 0,
    "pontos_cr10k": 0,
    "pontos_ld30k": 0,
    "pontos_total": 0,
    "pos_montanha": null,
    "pos_cr10k": null,
    "pos_ld30k": null,
    "pos_geral": null
  },
  {
    "atleta": "Ana Azevedo",
    "academia": "PULSE",
    "equipe": "PRO FEMININO",
    "categoria": "Feminino",
    "ftp_final": "00:00:10",
    "ftp_final_s": 10,
    "montanha": "00:28:44",
    "montanha_s": 1724,
    "cr10k": "00:53:20",
    "cr10k_s": 3200,
    "ld30k": "01:22:14",
    "ld30k_s": 4934,
    "tempo_total": "01:22:14",
    "tempo_total_s": 4934,
    "provas": 3,
    "completo": true,
    "pontos_montanha": 15,
    "pontos_cr10k": 7,
    "pontos_ld30k": 7,
    "pontos_total": 29,
    "pos_montanha": 4,
    "pos_cr10k": 8,
    "pos_ld30k": 8,
    "pos_geral": 15,
    "pos_geral_categoria": 4
  },
  {
    "atleta": "Renata Ivia",
    "academia": "BT NS",
    "equipe": "PRO FEMININO",
    "categoria": "Feminino",
    "ftp_final": "00:00:15",
    "ftp_final_s": 15,
    "montanha": null,
    "montanha_s": null,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": "00:00:15",
    "tempo_total_s": 15,
    "provas": 1,
    "completo": false,
    "pontos_montanha": 0,
    "pontos_cr10k": 0,
    "pontos_ld30k": 0,
    "pontos_total": 0,
    "pos_montanha": null,
    "pos_cr10k": null,
    "pos_ld30k": null,
    "pos_geral": null
  },
  {
    "atleta": "Washington Filho",
    "academia": "BT NS",
    "equipe": "PRO MASCULINO",
    "categoria": "Masculino",
    "ftp_final": "00:00:14",
    "ftp_final_s": 14,
    "montanha": "00:24:44",
    "montanha_s": 1484,
    "cr10k": "00:46:22",
    "cr10k_s": 2782,
    "ld30k": "01:11:20",
    "ld30k_s": 4280,
    "tempo_total": "01:11:20",
    "tempo_total_s": 4280,
    "provas": 3,
    "completo": true,
    "pontos_montanha": 17,
    "pontos_cr10k": 11,
    "pontos_ld30k": 7,
    "pontos_total": 35,
    "pos_montanha": 3,
    "pos_cr10k": 6,
    "pos_ld30k": 8,
    "pos_geral": 9,
    "pos_geral_categoria": 3
  },
  {
    "atleta": "Orlando Cunha",
    "academia": "BT TIROL",
    "equipe": "MASTER",
    "categoria": "Masculino",
    "ftp_final": "00:00:16",
    "ftp_final_s": 16,
    "montanha": "00:24:51",
    "montanha_s": 1491,
    "cr10k": "00:46:17",
    "cr10k_s": 2777,
    "ld30k": "01:11:24",
    "ld30k_s": 4284,
    "tempo_total": "01:11:24",
    "tempo_total_s": 4284,
    "provas": 3,
    "completo": true,
    "pontos_montanha": 25,
    "pontos_cr10k": 7,
    "pontos_ld30k": 1,
    "pontos_total": 33,
    "pos_montanha": 1,
    "pos_cr10k": 8,
    "pos_ld30k": 11,
    "pos_geral": 10,
    "pos_geral_categoria": 1
  },
  {
    "atleta": "Ana P. Mendes",
    "academia": "BT TIROL",
    "equipe": "MASTER",
    "categoria": "Feminino",
    "ftp_final": "00:00:14",
    "ftp_final_s": 14,
    "montanha": "00:28:43",
    "montanha_s": 1723,
    "cr10k": "00:53:29",
    "cr10k_s": 3209,
    "ld30k": "01:22:26",
    "ld30k_s": 4946,
    "tempo_total": "01:22:26",
    "tempo_total_s": 4946,
    "provas": 3,
    "completo": true,
    "pontos_montanha": 11,
    "pontos_cr10k": 1,
    "pontos_ld30k": 0,
    "pontos_total": 12,
    "pos_montanha": 6,
    "pos_cr10k": 11,
    "pos_ld30k": 14,
    "pos_geral": 16,
    "pos_geral_categoria": 4
  },
  {
    "atleta": "Fabrício Barros",
    "academia": "BT TIROL",
    "equipe": "ELITE MASCULINO",
    "categoria": "Masculino",
    "ftp_final": "00:00:17",
    "ftp_final_s": 17,
    "montanha": "00:25:00",
    "montanha_s": 1500,
    "cr10k": "00:46:13",
    "cr10k_s": 2773,
    "ld30k": "01:11:30",
    "ld30k_s": 4290,
    "tempo_total": "01:11:30",
    "tempo_total_s": 4290,
    "provas": 3,
    "completo": true,
    "pontos_montanha": 7,
    "pontos_cr10k": 3,
    "pontos_ld30k": 1,
    "pontos_total": 11,
    "pos_montanha": 8,
    "pos_cr10k": 10,
    "pos_ld30k": 11,
    "pos_geral": 11,
    "pos_geral_categoria": 6
  },
  {
    "atleta": "Armando Nóbrega",
    "academia": "AABB",
    "equipe": "MASTER",
    "categoria": "Masculino",
    "ftp_final": "00:00:15",
    "ftp_final_s": 15,
    "montanha": null,
    "montanha_s": null,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:49:22",
    "ld30k_s": 2962,
    "tempo_total": "00:49:37",
    "tempo_total_s": 2977,
    "provas": 2,
    "completo": false,
    "pontos_montanha": 0,
    "pontos_cr10k": 0,
    "pontos_ld30k": 13,
    "pontos_total": 13,
    "pos_montanha": null,
    "pos_cr10k": null,
    "pos_ld30k": 5,
    "pos_geral": null
  },
  {
    "atleta": "César Maia",
    "academia": "AABB",
    "equipe": "PRO MASCULINO",
    "categoria": "Masculino",
    "ftp_final": "00:00:16",
    "ftp_final_s": 16,
    "montanha": null,
    "montanha_s": null,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:45:50",
    "ld30k_s": 2750,
    "tempo_total": "00:46:06",
    "tempo_total_s": 2766,
    "provas": 2,
    "completo": false,
    "pontos_montanha": 0,
    "pontos_cr10k": 0,
    "pontos_ld30k": 25,
    "pontos_total": 25,
    "pos_montanha": null,
    "pos_cr10k": null,
    "pos_ld30k": 1,
    "pos_geral": null
  },
  {
    "atleta": "Isadora Meybel",
    "academia": "BT NS",
    "equipe": "PRO FEMININO",
    "categoria": "Feminino",
    "ftp_final": "00:00:11",
    "ftp_final_s": 11,
    "montanha": "00:29:28",
    "montanha_s": 1768,
    "cr10k": "00:52:51",
    "cr10k_s": 3171,
    "ld30k": "01:22:30",
    "ld30k_s": 4950,
    "tempo_total": "01:22:30",
    "tempo_total_s": 4950,
    "provas": 3,
    "completo": true,
    "pontos_montanha": 9,
    "pontos_cr10k": 13,
    "pontos_ld30k": 5,
    "pontos_total": 27,
    "pos_montanha": 7,
    "pos_cr10k": 5,
    "pos_ld30k": 9,
    "pos_geral": 17,
    "pos_geral_categoria": 5
  },
  {
    "atleta": "Allyne França",
    "academia": "AABB",
    "equipe": "PRO FEMININO",
    "categoria": "Feminino",
    "ftp_final": "00:00:12",
    "ftp_final_s": 12,
    "montanha": "00:29:15",
    "montanha_s": 1755,
    "cr10k": "00:53:07",
    "cr10k_s": 3187,
    "ld30k": "01:22:34",
    "ld30k_s": 4954,
    "tempo_total": "01:22:34",
    "tempo_total_s": 4954,
    "provas": 3,
    "completo": true,
    "pontos_montanha": 11,
    "pontos_cr10k": 9,
    "pontos_ld30k": 3,
    "pontos_total": 23,
    "pos_montanha": 6,
    "pos_cr10k": 7,
    "pos_ld30k": 10,
    "pos_geral": 18,
    "pos_geral_categoria": 6
  },
  {
    "atleta": "Júlia Rocha",
    "academia": "PULSE",
    "equipe": "SUB-26",
    "categoria": "Feminino",
    "ftp_final": "00:00:10",
    "ftp_final_s": 10,
    "montanha": "00:28:40",
    "montanha_s": 1720,
    "cr10k": "00:54:17",
    "cr10k_s": 3257,
    "ld30k": "01:23:07",
    "ld30k_s": 4987,
    "tempo_total": "01:23:07",
    "tempo_total_s": 4987,
    "provas": 3,
    "completo": true,
    "pontos_montanha": 11,
    "pontos_cr10k": 0,
    "pontos_ld30k": 0,
    "pontos_total": 11,
    "pos_montanha": 6,
    "pos_cr10k": 12,
    "pos_ld30k": 13,
    "pos_geral": 19,
    "pos_geral_categoria": 5
  },
  {
    "atleta": "Luna Melo",
    "academia": "BT TIROL",
    "equipe": "SUB-26",
    "categoria": "Feminino",
    "ftp_final": "00:00:17",
    "ftp_final_s": 17,
    "montanha": "00:31:36",
    "montanha_s": 1896,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": "00:31:53",
    "tempo_total_s": 1913,
    "provas": 2,
    "completo": false,
    "pontos_montanha": 5,
    "pontos_cr10k": 0,
    "pontos_ld30k": 0,
    "pontos_total": 5,
    "pos_montanha": 9,
    "pos_cr10k": null,
    "pos_ld30k": null,
    "pos_geral": null
  },
  {
    "atleta": "Duduzinho",
    "academia": "BT TIROL",
    "equipe": "SUB-26",
    "categoria": "Masculino",
    "ftp_final": "00:00:16",
    "ftp_final_s": 16,
    "montanha": null,
    "montanha_s": null,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "01:01:48",
    "ld30k_s": 3708,
    "tempo_total": "01:02:04",
    "tempo_total_s": 3724,
    "provas": 2,
    "completo": false,
    "pontos_montanha": 0,
    "pontos_cr10k": 0,
    "pontos_ld30k": 7,
    "pontos_total": 7,
    "pos_montanha": null,
    "pos_cr10k": null,
    "pos_ld30k": 8,
    "pos_geral": null
  },
  {
    "atleta": "Edu Silva",
    "academia": "BT NS",
    "equipe": "PRO MASCULINO",
    "categoria": "Masculino",
    "ftp_final": "00:00:16",
    "ftp_final_s": 16,
    "montanha": null,
    "montanha_s": null,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:46:17",
    "ld30k_s": 2777,
    "tempo_total": "00:46:33",
    "tempo_total_s": 2793,
    "provas": 2,
    "completo": false,
    "pontos_montanha": 0,
    "pontos_cr10k": 0,
    "pontos_ld30k": 20,
    "pontos_total": 20,
    "pos_montanha": null,
    "pos_cr10k": null,
    "pos_ld30k": 2,
    "pos_geral": null
  },
  {
    "atleta": "Victor Barbosa",
    "academia": "PULSE",
    "equipe": "SUB-26",
    "categoria": "Masculino",
    "ftp_final": "00:00:15",
    "ftp_final_s": 15,
    "montanha": "00:25:16",
    "montanha_s": 1516,
    "cr10k": "00:48:10",
    "cr10k_s": 2890,
    "ld30k": "01:13:41",
    "ld30k_s": 4421,
    "tempo_total": "01:13:41",
    "tempo_total_s": 4421,
    "provas": 3,
    "completo": true,
    "pontos_montanha": 20,
    "pontos_cr10k": 7,
    "pontos_ld30k": 3,
    "pontos_total": 30,
    "pos_montanha": 2,
    "pos_cr10k": 8,
    "pos_ld30k": 10,
    "pos_geral": 12,
    "pos_geral_categoria": 2
  },
  {
    "atleta": "Onaldo Dantas",
    "academia": "AABB",
    "equipe": "MASTER",
    "categoria": "Masculino",
    "ftp_final": "00:00:16",
    "ftp_final_s": 16,
    "montanha": "00:25:45",
    "montanha_s": 1545,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": "00:26:01",
    "tempo_total_s": 1561,
    "provas": 2,
    "completo": false,
    "pontos_montanha": 17,
    "pontos_cr10k": 0,
    "pontos_ld30k": 0,
    "pontos_total": 17,
    "pos_montanha": 3,
    "pos_cr10k": null,
    "pos_ld30k": null,
    "pos_geral": null
  },
  {
    "atleta": "Alberto",
    "academia": "PULSE",
    "equipe": "MASTER",
    "categoria": "Masculino",
    "ftp_final": "00:00:18",
    "ftp_final_s": 18,
    "montanha": "00:25:17",
    "montanha_s": 1517,
    "cr10k": "00:48:24",
    "cr10k_s": 2904,
    "ld30k": "01:13:59",
    "ld30k_s": 4439,
    "tempo_total": "01:13:59",
    "tempo_total_s": 4439,
    "provas": 3,
    "completo": true,
    "pontos_montanha": 20,
    "pontos_cr10k": 5,
    "pontos_ld30k": 0,
    "pontos_total": 25,
    "pos_montanha": 2,
    "pos_cr10k": 9,
    "pos_ld30k": 12,
    "pos_geral": 13,
    "pos_geral_categoria": 2
  },
  {
    "atleta": "Luerber Oscar",
    "academia": "PULSE",
    "equipe": "PRO MASCULINO",
    "categoria": "Masculino",
    "ftp_final": "00:00:15",
    "ftp_final_s": 15,
    "montanha": "00:25:34",
    "montanha_s": 1534,
    "cr10k": "00:48:12",
    "cr10k_s": 2892,
    "ld30k": "01:14:01",
    "ld30k_s": 4441,
    "tempo_total": "01:14:01",
    "tempo_total_s": 4441,
    "provas": 3,
    "completo": true,
    "pontos_montanha": 11,
    "pontos_cr10k": 9,
    "pontos_ld30k": 5,
    "pontos_total": 25,
    "pos_montanha": 6,
    "pos_cr10k": 7,
    "pos_ld30k": 9,
    "pos_geral": 14,
    "pos_geral_categoria": 4
  },
  {
    "atleta": "Gisele",
    "academia": "PULSE",
    "equipe": "ELITE FEMININO",
    "categoria": "Feminino",
    "ftp_final": "00:00:17",
    "ftp_final_s": 17,
    "montanha": null,
    "montanha_s": null,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": "00:00:17",
    "tempo_total_s": 17,
    "provas": 1,
    "completo": false,
    "pontos_montanha": 0,
    "pontos_cr10k": 0,
    "pontos_ld30k": 0,
    "pontos_total": 0,
    "pos_montanha": null,
    "pos_cr10k": null,
    "pos_ld30k": null,
    "pos_geral": null
  },
  {
    "atleta": "EDUARDO",
    "academia": "BT TIROL",
    "equipe": "ELITE MASCULINO",
    "categoria": "Masculino",
    "ftp_final": "00:00:17",
    "ftp_final_s": 17,
    "montanha": null,
    "montanha_s": null,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": "00:00:17",
    "tempo_total_s": 17,
    "provas": 1,
    "completo": false,
    "pontos_montanha": 0,
    "pontos_cr10k": 0,
    "pontos_ld30k": 0,
    "pontos_total": 0,
    "pos_montanha": null,
    "pos_cr10k": null,
    "pos_ld30k": null,
    "pos_geral": null
  },
  {
    "atleta": "Luciana Maria",
    "academia": "AABB",
    "equipe": "SUB-26",
    "categoria": "Feminino",
    "ftp_final": "00:00:19",
    "ftp_final_s": 19,
    "montanha": "00:28:31",
    "montanha_s": 1711,
    "cr10k": "00:54:27",
    "cr10k_s": 3267,
    "ld30k": "01:23:17",
    "ld30k_s": 4997,
    "tempo_total": "01:23:17",
    "tempo_total_s": 4997,
    "provas": 3,
    "completo": true,
    "pontos_montanha": 13,
    "pontos_cr10k": 0,
    "pontos_ld30k": 0,
    "pontos_total": 13,
    "pos_montanha": 5,
    "pos_cr10k": 13,
    "pos_ld30k": 14,
    "pos_geral": 20,
    "pos_geral_categoria": 6
  },
  {
    "atleta": "Wilson Chacon",
    "academia": "BT TIROL",
    "equipe": "MASTER",
    "categoria": "Masculino",
    "ftp_final": "00:00:17",
    "ftp_final_s": 17,
    "montanha": null,
    "montanha_s": null,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:49:00",
    "ld30k_s": 2940,
    "tempo_total": "00:49:17",
    "tempo_total_s": 2957,
    "provas": 2,
    "completo": false,
    "pontos_montanha": 0,
    "pontos_cr10k": 0,
    "pontos_ld30k": 15,
    "pontos_total": 15,
    "pos_montanha": null,
    "pos_cr10k": null,
    "pos_ld30k": 4,
    "pos_geral": null
  },
  {
    "atleta": "Rogério Dantas",
    "academia": "BT NS",
    "equipe": "MASTER",
    "categoria": "Masculino",
    "ftp_final": "00:00:17",
    "ftp_final_s": 17,
    "montanha": "00:28:21",
    "montanha_s": 1701,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": "00:28:38",
    "tempo_total_s": 1718,
    "provas": 2,
    "completo": false,
    "pontos_montanha": 13,
    "pontos_cr10k": 0,
    "pontos_ld30k": 0,
    "pontos_total": 13,
    "pos_montanha": 5,
    "pos_cr10k": null,
    "pos_ld30k": null,
    "pos_geral": null
  },
  {
    "atleta": "Dowglas",
    "academia": "BT NS",
    "equipe": "PRO MASCULINO",
    "categoria": "Masculino",
    "ftp_final": "00:00:18",
    "ftp_final_s": 18,
    "montanha": null,
    "montanha_s": null,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": "00:00:18",
    "tempo_total_s": 18,
    "provas": 1,
    "completo": false,
    "pontos_montanha": 0,
    "pontos_cr10k": 0,
    "pontos_ld30k": 0,
    "pontos_total": 0,
    "pos_montanha": null,
    "pos_cr10k": null,
    "pos_ld30k": null,
    "pos_geral": null
  },
  {
    "atleta": "Vivi",
    "academia": "PULSE",
    "equipe": "PRO FEMININO",
    "categoria": "Feminino",
    "ftp_final": "00:00:18",
    "ftp_final_s": 18,
    "montanha": "00:30:32",
    "montanha_s": 1832,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": "00:30:50",
    "tempo_total_s": 1850,
    "provas": 2,
    "completo": false,
    "pontos_montanha": 3,
    "pontos_cr10k": 0,
    "pontos_ld30k": 0,
    "pontos_total": 3,
    "pos_montanha": 10,
    "pos_cr10k": null,
    "pos_ld30k": null,
    "pos_geral": null
  },
  {
    "atleta": "Laura Negreiros",
    "academia": "AABB",
    "equipe": "SUB-26",
    "categoria": "Feminino",
    "ftp_final": "00:00:20",
    "ftp_final_s": 20,
    "montanha": "00:29:43",
    "montanha_s": 1783,
    "cr10k": "00:53:19",
    "cr10k_s": 3199,
    "ld30k": "01:23:22",
    "ld30k_s": 5002,
    "tempo_total": "01:23:22",
    "tempo_total_s": 5002,
    "provas": 3,
    "completo": true,
    "pontos_montanha": 7,
    "pontos_cr10k": 1,
    "pontos_ld30k": 0,
    "pontos_total": 8,
    "pos_montanha": 8,
    "pos_cr10k": 11,
    "pos_ld30k": 15,
    "pos_geral": 21,
    "pos_geral_categoria": 7
  },
  {
    "atleta": "Fernanda Fernandes",
    "academia": "AABB",
    "equipe": "MASTER",
    "categoria": "Feminino",
    "ftp_final": "00:00:20",
    "ftp_final_s": 20,
    "montanha": "00:30:19",
    "montanha_s": 1819,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": "00:30:39",
    "tempo_total_s": 1839,
    "provas": 2,
    "completo": false,
    "pontos_montanha": 7,
    "pontos_cr10k": 0,
    "pontos_ld30k": 0,
    "pontos_total": 7,
    "pos_montanha": 8,
    "pos_cr10k": null,
    "pos_ld30k": null,
    "pos_geral": null
  },
  {
    "atleta": "João Menezes",
    "academia": "AABB",
    "equipe": "SUB-26",
    "categoria": "Masculino",
    "ftp_final": "00:00:11",
    "ftp_final_s": 11,
    "montanha": "00:25:52",
    "montanha_s": 1552,
    "cr10k": "00:48:58",
    "cr10k_s": 2938,
    "ld30k": "01:15:01",
    "ld30k_s": 4501,
    "tempo_total": "01:15:01",
    "tempo_total_s": 4501,
    "provas": 3,
    "completo": true,
    "pontos_montanha": 17,
    "pontos_cr10k": 5,
    "pontos_ld30k": 1,
    "pontos_total": 23,
    "pos_montanha": 3,
    "pos_cr10k": 9,
    "pos_ld30k": 11,
    "pos_geral": 15,
    "pos_geral_categoria": 3
  },
  {
    "atleta": "Matheus Alves",
    "academia": "BT NS",
    "equipe": "SUB-26",
    "categoria": "Masculino",
    "ftp_final": "00:00:18",
    "ftp_final_s": 18,
    "montanha": null,
    "montanha_s": null,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:52:13",
    "ld30k_s": 3133,
    "tempo_total": "00:52:31",
    "tempo_total_s": 3151,
    "provas": 2,
    "completo": false,
    "pontos_montanha": 0,
    "pontos_cr10k": 0,
    "pontos_ld30k": 15,
    "pontos_total": 15,
    "pos_montanha": null,
    "pos_cr10k": null,
    "pos_ld30k": 4,
    "pos_geral": null
  },
  {
    "atleta": "JESSICA",
    "academia": "BT NS",
    "equipe": "SUB-26",
    "categoria": "Feminino",
    "ftp_final": "00:00:20",
    "ftp_final_s": 20,
    "montanha": null,
    "montanha_s": null,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": "00:00:20",
    "tempo_total_s": 20,
    "provas": 1,
    "completo": false,
    "pontos_montanha": 0,
    "pontos_cr10k": 0,
    "pontos_ld30k": 0,
    "pontos_total": 0,
    "pos_montanha": null,
    "pos_cr10k": null,
    "pos_ld30k": null,
    "pos_geral": null
  },
  {
    "atleta": "Giuly Giardinni",
    "academia": "AABB",
    "equipe": "PRO FEMININO",
    "categoria": "Feminino",
    "ftp_final": "00:00:42",
    "ftp_final_s": 42,
    "montanha": "00:28:07",
    "montanha_s": 1687,
    "cr10k": "00:54:40",
    "cr10k_s": 3280,
    "ld30k": "01:23:29",
    "ld30k_s": 5009,
    "tempo_total": "01:23:29",
    "tempo_total_s": 5009,
    "provas": 3,
    "completo": true,
    "pontos_montanha": 20,
    "pontos_cr10k": 5,
    "pontos_ld30k": 1,
    "pontos_total": 26,
    "pos_montanha": 2,
    "pos_cr10k": 9,
    "pos_ld30k": 11,
    "pos_geral": 22,
    "pos_geral_categoria": 7
  },
  {
    "atleta": "Elistenio Pai",
    "academia": "BT TIROL",
    "equipe": "PRO MASCULINO",
    "categoria": "Masculino",
    "ftp_final": "00:00:19",
    "ftp_final_s": 19,
    "montanha": "00:26:42",
    "montanha_s": 1602,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": "00:27:01",
    "tempo_total_s": 1621,
    "provas": 2,
    "completo": false,
    "pontos_montanha": 7,
    "pontos_cr10k": 0,
    "pontos_ld30k": 0,
    "pontos_total": 7,
    "pos_montanha": 8,
    "pos_cr10k": null,
    "pos_ld30k": null,
    "pos_geral": null
  },
  {
    "atleta": "Fernanda Veloso",
    "academia": "PULSE",
    "equipe": "PRO FEMININO",
    "categoria": "Feminino",
    "ftp_final": "00:00:21",
    "ftp_final_s": 21,
    "montanha": "00:30:00",
    "montanha_s": 1800,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": "00:30:21",
    "tempo_total_s": 1821,
    "provas": 2,
    "completo": false,
    "pontos_montanha": 5,
    "pontos_cr10k": 0,
    "pontos_ld30k": 0,
    "pontos_total": 5,
    "pos_montanha": 9,
    "pos_cr10k": null,
    "pos_ld30k": null,
    "pos_geral": null
  },
  {
    "atleta": "Katia Cunha",
    "academia": "PULSE",
    "equipe": "MASTER",
    "categoria": "Feminino",
    "ftp_final": "00:00:16",
    "ftp_final_s": 16,
    "montanha": "00:28:03",
    "montanha_s": 1683,
    "cr10k": "00:55:30",
    "cr10k_s": 3330,
    "ld30k": "01:23:49",
    "ld30k_s": 5029,
    "tempo_total": "01:23:49",
    "tempo_total_s": 5029,
    "provas": 3,
    "completo": true,
    "pontos_montanha": 15,
    "pontos_cr10k": 0,
    "pontos_ld30k": 0,
    "pontos_total": 15,
    "pos_montanha": 4,
    "pos_cr10k": 12,
    "pos_ld30k": 15,
    "pos_geral": 23,
    "pos_geral_categoria": 5
  },
  {
    "atleta": "GERUSIA",
    "academia": "BT NS",
    "equipe": "MASTER",
    "categoria": "Feminino",
    "ftp_final": "00:00:21",
    "ftp_final_s": 21,
    "montanha": null,
    "montanha_s": null,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:53:40",
    "ld30k_s": 3220,
    "tempo_total": "00:54:01",
    "tempo_total_s": 3241,
    "provas": 2,
    "completo": false,
    "pontos_montanha": 0,
    "pontos_cr10k": 0,
    "pontos_ld30k": 5,
    "pontos_total": 5,
    "pos_montanha": null,
    "pos_cr10k": null,
    "pos_ld30k": 9,
    "pos_geral": null
  },
  {
    "atleta": "Maurício",
    "academia": "PULSE",
    "equipe": "MASTER",
    "categoria": "Masculino",
    "ftp_final": "00:00:20",
    "ftp_final_s": 20,
    "montanha": null,
    "montanha_s": null,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:51:31",
    "ld30k_s": 3091,
    "tempo_total": "00:51:51",
    "tempo_total_s": 3111,
    "provas": 2,
    "completo": false,
    "pontos_montanha": 0,
    "pontos_cr10k": 0,
    "pontos_ld30k": 9,
    "pontos_total": 9,
    "pos_montanha": null,
    "pos_cr10k": null,
    "pos_ld30k": 7,
    "pos_geral": null
  },
  {
    "atleta": "Chiyo da Silva",
    "academia": "AABB",
    "equipe": "MASTER",
    "categoria": "Feminino",
    "ftp_final": "00:00:13",
    "ftp_final_s": 13,
    "montanha": "00:30:50",
    "montanha_s": 1850,
    "cr10k": "00:56:50",
    "cr10k_s": 3410,
    "ld30k": "01:27:53",
    "ld30k_s": 5273,
    "tempo_total": "01:27:53",
    "tempo_total_s": 5273,
    "provas": 3,
    "completo": true,
    "pontos_montanha": 5,
    "pontos_cr10k": 0,
    "pontos_ld30k": 0,
    "pontos_total": 5,
    "pos_montanha": 9,
    "pos_cr10k": 13,
    "pos_ld30k": 16,
    "pos_geral": 24,
    "pos_geral_categoria": 6
  },
  {
    "atleta": "Carol Negreiros",
    "academia": "PULSE",
    "equipe": "SUB-26",
    "categoria": "Feminino",
    "ftp_final": "00:00:22",
    "ftp_final_s": 22,
    "montanha": "00:32:27",
    "montanha_s": 1947,
    "cr10k": "01:07:11",
    "cr10k_s": 4031,
    "ld30k": "01:40:00",
    "ld30k_s": 6000,
    "tempo_total": "01:40:00",
    "tempo_total_s": 6000,
    "provas": 3,
    "completo": true,
    "pontos_montanha": 3,
    "pontos_cr10k": 0,
    "pontos_ld30k": 0,
    "pontos_total": 3,
    "pos_montanha": 10,
    "pos_cr10k": 14,
    "pos_ld30k": 16,
    "pos_geral": 25,
    "pos_geral_categoria": 8
  },
  {
    "atleta": "Artur Sena",
    "academia": "BT NS",
    "equipe": "SUB-26",
    "categoria": "Masculino",
    "ftp_final": "00:00:22",
    "ftp_final_s": 22,
    "montanha": "00:28:04",
    "montanha_s": 1684,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": "00:28:26",
    "tempo_total_s": 1706,
    "provas": 2,
    "completo": false,
    "pontos_montanha": 15,
    "pontos_cr10k": 0,
    "pontos_ld30k": 0,
    "pontos_total": 15,
    "pos_montanha": 4,
    "pos_cr10k": null,
    "pos_ld30k": null,
    "pos_geral": null
  },
  {
    "atleta": "Maria Karolina",
    "academia": "BT TIROL",
    "equipe": "PRO FEMININO",
    "categoria": "Feminino",
    "ftp_final": null,
    "ftp_final_s": null,
    "montanha": null,
    "montanha_s": null,
    "cr10k": "00:30:47",
    "cr10k_s": 1847,
    "ld30k": "00:54:46",
    "ld30k_s": 3286,
    "tempo_total": "01:25:33",
    "tempo_total_s": 5133,
    "provas": 2,
    "completo": false,
    "pontos_montanha": 0,
    "pontos_cr10k": 20,
    "pontos_ld30k": 17,
    "pontos_total": 37,
    "pos_montanha": null,
    "pos_cr10k": 2,
    "pos_ld30k": 3,
    "pos_geral": null
  },
  {
    "atleta": "Luiz César",
    "academia": "AABB",
    "equipe": "SUB-26",
    "categoria": "Masculino",
    "ftp_final": "00:00:23",
    "ftp_final_s": 23,
    "montanha": null,
    "montanha_s": null,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": "00:00:23",
    "tempo_total_s": 23,
    "provas": 1,
    "completo": false,
    "pontos_montanha": 0,
    "pontos_cr10k": 0,
    "pontos_ld30k": 0,
    "pontos_total": 0,
    "pos_montanha": null,
    "pos_cr10k": null,
    "pos_ld30k": null,
    "pos_geral": null
  },
  {
    "atleta": "Danilo Vale",
    "academia": "BT TIROL",
    "equipe": "ELITE MASCULINO",
    "categoria": "Masculino",
    "ftp_final": null,
    "ftp_final_s": null,
    "montanha": null,
    "montanha_s": null,
    "cr10k": "00:23:55",
    "cr10k_s": 1435,
    "ld30k": "00:44:28",
    "ld30k_s": 2668,
    "tempo_total": "01:08:23",
    "tempo_total_s": 4103,
    "provas": 2,
    "completo": false,
    "pontos_montanha": 0,
    "pontos_cr10k": 20,
    "pontos_ld30k": 17,
    "pontos_total": 37,
    "pos_montanha": null,
    "pos_cr10k": 2,
    "pos_ld30k": 3,
    "pos_geral": null
  }
];

const PONTOS_EQUIPE_CAT = {
  "ELITE FEMININO": {
    "Montanha": {
      "PULSE": {
        "soma_s": 3379,
        "soma_str": "00:56:19",
        "atletas": [
          "Hívila Moreira",
          "Karine Symonir"
        ],
        "pontos": 17,
        "posicao": 3
      },
      "BT TIROL": {
        "soma_s": 3184,
        "soma_str": "00:53:04",
        "atletas": [
          "Andréia Medeiros",
          "Renata Seixas"
        ],
        "pontos": 25,
        "posicao": 1
      },
      "AABB": {
        "soma_s": 3304,
        "soma_str": "00:55:04",
        "atletas": [
          "Sarah Brito",
          "Silvia Drummond"
        ],
        "pontos": 20,
        "posicao": 2
      },
      "BT NS": {
        "soma_s": 4775,
        "soma_str": "01:19:35",
        "atletas": [
          "Alini Brito",
          "Simone Ribeiro",
          "Joyce Ribeiro"
        ],
        "pontos": 15,
        "posicao": 4
      }
    },
    "Contrarrelógio 10k": {
      "PULSE": {
        "soma_s": 7826,
        "soma_str": "02:10:26",
        "atletas": [
          "Cris Diniz",
          "Karine Symonir",
          "Hívila Moreira"
        ],
        "pontos": 17,
        "posicao": 3
      },
      "BT TIROL": {
        "soma_s": 7495,
        "soma_str": "02:04:55",
        "atletas": [
          "Raissa Georgia",
          "Andréia Medeiros",
          "Renata Seixas"
        ],
        "pontos": 25,
        "posicao": 1
      },
      "AABB": {
        "soma_s": 7619,
        "soma_str": "02:06:59",
        "atletas": [
          "Lydia Tinôco",
          "Silvia Drummond",
          "Sarah Brito"
        ],
        "pontos": 20,
        "posicao": 2
      },
      "BT NS": {
        "soma_s": 8677,
        "soma_str": "02:24:37",
        "atletas": [
          "Joyce Ribeiro",
          "Simone Ribeiro",
          "Alini Brito"
        ],
        "pontos": 15,
        "posicao": 4
      }
    },
    "Longa Distância 30k": {
      "PULSE": {
        "soma_s": 12517,
        "soma_str": "03:28:37",
        "atletas": [
          "Cris Diniz",
          "Hívila Moreira",
          "Karine Symonir"
        ],
        "pontos": 17,
        "posicao": 3
      },
      "BT TIROL": {
        "soma_s": 12134,
        "soma_str": "03:22:14",
        "atletas": [
          "Raissa Georgia",
          "Andréia Medeiros",
          "Renata Seixas"
        ],
        "pontos": 25,
        "posicao": 1
      },
      "AABB": {
        "soma_s": 12458,
        "soma_str": "03:27:38",
        "atletas": [
          "Lydia Tinôco",
          "Silvia Drummond",
          "Sarah Brito"
        ],
        "pontos": 20,
        "posicao": 2
      },
      "BT NS": {
        "soma_s": 13477,
        "soma_str": "03:44:37",
        "atletas": [
          "Simone Ribeiro",
          "Alini Brito",
          "Joyce Ribeiro"
        ],
        "pontos": 15,
        "posicao": 4
      }
    }
  },
  "ELITE MASCULINO": {
    "Montanha": {
      "BT NS": {
        "soma_s": 4297,
        "soma_str": "01:11:37",
        "atletas": [
          "Omar Dantas",
          "Neto Xavier",
          "Gringo"
        ],
        "pontos": 15,
        "posicao": 4
      },
      "PULSE": {
        "soma_s": 2816,
        "soma_str": "00:46:56",
        "atletas": [
          "Lucas Leonardo",
          "Diogo Almeida"
        ],
        "pontos": 25,
        "posicao": 1
      },
      "AABB": {
        "soma_s": 2836,
        "soma_str": "00:47:16",
        "atletas": [
          "Genival Ferreira",
          "Bira Carratu"
        ],
        "pontos": 20,
        "posicao": 2
      },
      "BT TIROL": {
        "soma_s": 2884,
        "soma_str": "00:48:04",
        "atletas": [
          "Sergio Torralba",
          "Fabrício Barros"
        ],
        "pontos": 17,
        "posicao": 3
      }
    },
    "Contrarrelógio 10k": {
      "BT NS": {
        "soma_s": 6716,
        "soma_str": "01:51:56",
        "atletas": [
          "Daniel Azevedo",
          "Omar Dantas",
          "Neto Xavier"
        ],
        "pontos": 17,
        "posicao": 3
      },
      "PULSE": {
        "soma_s": 4060,
        "soma_str": "01:07:40",
        "atletas": [
          "Rafael Povoas",
          "Lucas Leonardo"
        ],
        "pontos": 20,
        "posicao": 2
      },
      "AABB": {
        "soma_s": 4018,
        "soma_str": "01:06:58",
        "atletas": [
          "Sivonaldo Tercio",
          "Genival Ferreira"
        ],
        "pontos": 25,
        "posicao": 1
      },
      "BT TIROL": {
        "soma_s": 6723,
        "soma_str": "01:52:03",
        "atletas": [
          "Danilo Vale",
          "Sergio Torralba",
          "Fabrício Barros"
        ],
        "pontos": 15,
        "posicao": 4
      }
    },
    "Longa Distância 30k": {
      "BT NS": {
        "soma_s": 10637,
        "soma_str": "02:57:17",
        "atletas": [
          "Daniel Azevedo",
          "Omar Dantas",
          "Neto Xavier"
        ],
        "pontos": 17,
        "posicao": 3
      },
      "PULSE": {
        "soma_s": 6712,
        "soma_str": "01:51:52",
        "atletas": [
          "Rafael Povoas",
          "Lucas Leonardo"
        ],
        "pontos": 25,
        "posicao": 1
      },
      "AABB": {
        "soma_s": 9542,
        "soma_str": "02:39:02",
        "atletas": [
          "Sivonaldo Tercio",
          "Renato Araújo",
          "Genival Ferreira"
        ],
        "pontos": 20,
        "posicao": 2
      },
      "BT TIROL": {
        "soma_s": 10860,
        "soma_str": "03:01:00",
        "atletas": [
          "Danilo Vale",
          "Sergio Torralba",
          "Fabrício Barros"
        ],
        "pontos": 15,
        "posicao": 4
      }
    }
  },
  "PRO FEMININO": {
    "Montanha": {
      "PULSE": {
        "soma_s": 5356,
        "soma_str": "01:29:16",
        "atletas": [
          "Ana Azevedo",
          "Fernanda Veloso",
          "Vivi"
        ],
        "pontos": 15,
        "posicao": 4
      },
      "BT NS": {
        "soma_s": 3497,
        "soma_str": "00:58:17",
        "atletas": [
          "Beatriz Bezerra",
          "Isadora Meybel"
        ],
        "pontos": 20,
        "posicao": 2
      },
      "BT TIROL": {
        "soma_s": 3429,
        "soma_str": "00:57:09",
        "atletas": [
          "Andreia Araujo",
          "Vanessa Rodrigues"
        ],
        "pontos": 25,
        "posicao": 1
      },
      "AABB": {
        "soma_s": 5161,
        "soma_str": "01:26:01",
        "atletas": [
          "Giuly Giardinni",
          "Camila Mota",
          "Allyne França"
        ],
        "pontos": 17,
        "posicao": 3
      }
    },
    "Contrarrelógio 10k": {
      "PULSE": {
        "soma_s": 3200,
        "soma_str": "00:53:20",
        "atletas": [
          "Ana Azevedo"
        ],
        "pontos": 25,
        "posicao": 1
      },
      "BT NS": {
        "soma_s": 7954,
        "soma_str": "02:12:34",
        "atletas": [
          "Lívia Revoredo",
          "Isadora Meybel",
          "Beatriz Bezerra"
        ],
        "pontos": 17,
        "posicao": 3
      },
      "BT TIROL": {
        "soma_s": 4991,
        "soma_str": "01:23:11",
        "atletas": [
          "Maria Karolina",
          "Andreia Araujo"
        ],
        "pontos": 20,
        "posicao": 2
      },
      "AABB": {
        "soma_s": 9634,
        "soma_str": "02:40:34",
        "atletas": [
          "Camila Mota",
          "Allyne França",
          "Giuly Giardinni"
        ],
        "pontos": 15,
        "posicao": 4
      }
    },
    "Longa Distância 30k": {
      "PULSE": {
        "soma_s": 8534,
        "soma_str": "02:22:14",
        "atletas": [
          "Adriana Melo",
          "Ana Azevedo"
        ],
        "pontos": 25,
        "posicao": 1
      },
      "BT NS": {
        "soma_s": 12830,
        "soma_str": "03:33:50",
        "atletas": [
          "Lívia Revoredo",
          "Beatriz Bezerra",
          "Isadora Meybel"
        ],
        "pontos": 17,
        "posicao": 3
      },
      "BT TIROL": {
        "soma_s": 11326,
        "soma_str": "03:08:46",
        "atletas": [
          "Heloisa Lopes",
          "Maria Karolina",
          "Andreia Araujo"
        ],
        "pontos": 20,
        "posicao": 2
      },
      "AABB": {
        "soma_s": 14863,
        "soma_str": "04:07:43",
        "atletas": [
          "Camila Mota",
          "Allyne França",
          "Giuly Giardinni"
        ],
        "pontos": 15,
        "posicao": 4
      }
    }
  },
  "PRO MASCULINO": {
    "Montanha": {
      "BT TIROL": {
        "soma_s": 3162,
        "soma_str": "00:52:42",
        "atletas": [
          "Carlos Thompson",
          "Elistenio Pai"
        ],
        "pontos": 17,
        "posicao": 3
      },
      "AABB": {
        "soma_s": 2959,
        "soma_str": "00:49:19",
        "atletas": [
          "Bruno Cabral",
          "José Arimatéia"
        ],
        "pontos": 20,
        "posicao": 2
      },
      "BT NS": {
        "soma_s": 1484,
        "soma_str": "00:24:44",
        "atletas": [
          "Washington Filho"
        ],
        "pontos": 25,
        "posicao": 1
      },
      "PULSE": {
        "soma_s": 4505,
        "soma_str": "01:15:05",
        "atletas": [
          "Arthur Dantas",
          "Olisuel Pereira",
          "Luerber Oscar"
        ],
        "pontos": 15,
        "posicao": 4
      }
    },
    "Contrarrelógio 10k": {
      "BT TIROL": {
        "soma_s": 1699,
        "soma_str": "00:28:19",
        "atletas": [
          "Igor Rosado"
        ],
        "pontos": 25,
        "posicao": 1
      },
      "AABB": {
        "soma_s": 4283,
        "soma_str": "01:11:23",
        "atletas": [
          "Haroldo Duarte",
          "José Arimatéia"
        ],
        "pontos": 20,
        "posicao": 2
      },
      "BT NS": {
        "soma_s": 4355,
        "soma_str": "01:12:35",
        "atletas": [
          "Kleber Gentil",
          "Washington Filho"
        ],
        "pontos": 17,
        "posicao": 3
      },
      "PULSE": {
        "soma_s": 5616,
        "soma_str": "01:33:36",
        "atletas": [
          "Olisuel Pereira",
          "Luerber Oscar"
        ],
        "pontos": 15,
        "posicao": 4
      }
    },
    "Longa Distância 30k": {
      "BT TIROL": {
        "soma_s": 0,
        "soma_str": null,
        "atletas": [],
        "pontos": 0,
        "posicao": null
      },
      "AABB": {
        "soma_s": 9897,
        "soma_str": "02:44:57",
        "atletas": [
          "César Maia",
          "Haroldo Duarte",
          "José Arimatéia"
        ],
        "pontos": 25,
        "posicao": 1
      },
      "BT NS": {
        "soma_s": 10250,
        "soma_str": "02:50:50",
        "atletas": [
          "Edu Silva",
          "Kleber Gentil",
          "Washington Filho"
        ],
        "pontos": 20,
        "posicao": 2
      },
      "PULSE": {
        "soma_s": 11577,
        "soma_str": "03:12:57",
        "atletas": [
          "Luiz Marcelo",
          "Olisuel Pereira",
          "Luerber Oscar"
        ],
        "pontos": 17,
        "posicao": 3
      }
    }
  },
  "MASTER": {
    "Montanha": {
      "PULSE": {
        "soma_s": 3200,
        "soma_str": "00:53:20",
        "atletas": [
          "Alberto",
          "Katia Cunha"
        ],
        "pontos": 25,
        "posicao": 1
      },
      "BT NS": {
        "soma_s": 3458,
        "soma_str": "00:57:38",
        "atletas": [
          "Rogério Dantas",
          "Socorro Linhares"
        ],
        "pontos": 17,
        "posicao": 3
      },
      "BT TIROL": {
        "soma_s": 3214,
        "soma_str": "00:53:34",
        "atletas": [
          "Orlando Cunha",
          "Ana P. Mendes"
        ],
        "pontos": 20,
        "posicao": 2
      },
      "AABB": {
        "soma_s": 5214,
        "soma_str": "01:26:54",
        "atletas": [
          "Onaldo Dantas",
          "Fernanda Fernandes",
          "Chiyo da Silva"
        ],
        "pontos": 15,
        "posicao": 4
      }
    },
    "Contrarrelógio 10k": {
      "PULSE": {
        "soma_s": 9511,
        "soma_str": "02:38:31",
        "atletas": [
          "Daniel Freire",
          "Alê Agra",
          "Alberto",
          "Katia Cunha"
        ],
        "pontos": 15,
        "posicao": 4
      },
      "BT NS": {
        "soma_s": 6321,
        "soma_str": "01:45:21",
        "atletas": [
          "Arthur Martins",
          "Alzinalia Lopes",
          "Socorro Linhares"
        ],
        "pontos": 20,
        "posicao": 2
      },
      "BT TIROL": {
        "soma_s": 9368,
        "soma_str": "02:36:08",
        "atletas": [
          "André Fernandes",
          "Sanzia Melo",
          "Orlando Cunha",
          "Ana P. Mendes"
        ],
        "pontos": 17,
        "posicao": 3
      },
      "AABB": {
        "soma_s": 4930,
        "soma_str": "01:22:10",
        "atletas": [
          "César Britto",
          "Chiyo da Silva"
        ],
        "pontos": 25,
        "posicao": 1
      }
    },
    "Longa Distância 30k": {
      "PULSE": {
        "soma_s": 15573,
        "soma_str": "04:19:33",
        "atletas": [
          "LIEGE",
          "Maurício",
          "Alberto",
          "Katia Cunha"
        ],
        "pontos": 15,
        "posicao": 4
      },
      "BT NS": {
        "soma_s": 13451,
        "soma_str": "03:44:11",
        "atletas": [
          "Raimundo Romão",
          "Arthur Martins",
          "GERUSIA",
          "Socorro Linhares"
        ],
        "pontos": 25,
        "posicao": 1
      },
      "BT TIROL": {
        "soma_s": 15381,
        "soma_str": "04:16:21",
        "atletas": [
          "Wilson Chacon",
          "CLAUDIA REGINA",
          "Orlando Cunha",
          "Ana P. Mendes"
        ],
        "pontos": 17,
        "posicao": 3
      },
      "AABB": {
        "soma_s": 14399,
        "soma_str": "03:59:59",
        "atletas": [
          "César Britto",
          "Armando Nóbrega",
          "Sheila Sales",
          "Chiyo da Silva"
        ],
        "pontos": 20,
        "posicao": 2
      }
    }
  },
  "SUB-26": {
    "Montanha": {
      "AABB": {
        "soma_s": 5046,
        "soma_str": "01:24:06",
        "atletas": [
          "João Menezes",
          "Luciana Maria",
          "Laura Negreiros"
        ],
        "pontos": 17,
        "posicao": 3
      },
      "BT TIROL": {
        "soma_s": 3398,
        "soma_str": "00:56:38",
        "atletas": [
          "Lucas Eurípides",
          "Luna Melo"
        ],
        "pontos": 25,
        "posicao": 1
      },
      "PULSE": {
        "soma_s": 5183,
        "soma_str": "01:26:23",
        "atletas": [
          "Victor Barbosa",
          "Júlia Rocha",
          "Carol Negreiros"
        ],
        "pontos": 15,
        "posicao": 4
      },
      "BT NS": {
        "soma_s": 3443,
        "soma_str": "00:57:23",
        "atletas": [
          "Artur Sena",
          "Livia Darc"
        ],
        "pontos": 20,
        "posicao": 2
      }
    },
    "Contrarrelógio 10k": {
      "AABB": {
        "soma_s": 11065,
        "soma_str": "03:04:25",
        "atletas": [
          "Allan Oliveira",
          "João Menezes",
          "Laura Negreiros",
          "Luciana Maria"
        ],
        "pontos": 17,
        "posicao": 3
      },
      "BT TIROL": {
        "soma_s": 6288,
        "soma_str": "01:44:48",
        "atletas": [
          "Isabel Lucena",
          "Elistenio Filho",
          "Lucas Eurípides"
        ],
        "pontos": 25,
        "posicao": 1
      },
      "PULSE": {
        "soma_s": 11791,
        "soma_str": "03:16:31",
        "atletas": [
          "Francisco Vito",
          "Victor Barbosa",
          "Júlia Rocha",
          "Carol Negreiros"
        ],
        "pontos": 15,
        "posicao": 4
      },
      "BT NS": {
        "soma_s": 6467,
        "soma_str": "01:47:47",
        "atletas": [
          "Joao Pedro",
          "Samara Silva",
          "Livia Darc"
        ],
        "pontos": 20,
        "posicao": 2
      }
    },
    "Longa Distância 30k": {
      "AABB": {
        "soma_s": 17637,
        "soma_str": "04:53:57",
        "atletas": [
          "Allan Oliveira",
          "João Menezes",
          "Luciana Maria",
          "Laura Negreiros"
        ],
        "pontos": 17,
        "posicao": 3
      },
      "BT TIROL": {
        "soma_s": 14239,
        "soma_str": "03:57:19",
        "atletas": [
          "Maria J nobrega",
          "Isabel Lucena",
          "Duduzinho",
          "Lucas Eurípides"
        ],
        "pontos": 25,
        "posicao": 1
      },
      "PULSE": {
        "soma_s": 18210,
        "soma_str": "05:03:30",
        "atletas": [
          "José Wilson",
          "Victor Barbosa",
          "Júlia Rocha",
          "Carol Negreiros"
        ],
        "pontos": 15,
        "posicao": 4
      },
      "BT NS": {
        "soma_s": 14352,
        "soma_str": "03:59:12",
        "atletas": [
          "Joao Pedro",
          "Matheus Alves",
          "Samara Silva",
          "Livia Darc"
        ],
        "pontos": 20,
        "posicao": 2
      }
    }
  }
};

const PONTOS_EQUIPE_TOTAL = {
  "PULSE": 333,
  "BT TIROL": 358,
  "AABB": 348,
  "BT NS": 332
};

const RANKING_GERAL_MASC = ["Omar Dantas", "Sergio Torralba", "Lucas Leonardo", "Neto Xavier", "Genival Ferreira", "Lucas Eurípides", "Olisuel Pereira", "José Arimatéia", "Washington Filho", "Orlando Cunha", "Fabrício Barros", "Victor Barbosa", "Alberto", "Luerber Oscar", "João Menezes"];

const RANKING_GERAL_FEM = ["Simone Ribeiro", "Andréia Medeiros", "Alini Brito", "Joyce Ribeiro", "Renata Seixas", "Silvia Drummond", "Sarah Brito", "Andreia Araujo", "Hívila Moreira", "Karine Symonir", "Livia Darc", "Camila Mota", "Beatriz Bezerra", "Socorro Linhares", "Ana Azevedo", "Ana P. Mendes", "Isadora Meybel", "Allyne França", "Júlia Rocha", "Luciana Maria", "Laura Negreiros", "Giuly Giardinni", "Katia Cunha", "Chiyo da Silva", "Carol Negreiros"];

