// Tour de Cicle Indoor - Dataset v2 (provas: FTP Final, Montanha, Longa Distância 30k)
// Contrarrelógio 10k: SEM DADOS AINDA

const PONTOS_RANKING = [25,20,17,15,13,11,9,7,5,3,1];

const ATLETAS = [
  {
    "atleta": "Adriana Caldas",
    "academia": "PULSE",
    "equipe": "PRO FEMININO",
    "categoria": "Feminino",
    "ftp_final": null,
    "ftp_final_s": null,
    "montanha": null,
    "montanha_s": null,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": null,
    "tempo_total_s": null,
    "provas": 0,
    "completo": false,
    "pontos_ftp": 0,
    "pos_ftp": null,
    "pontos_montanha": 0,
    "pos_montanha": null,
    "pontos_ld30k": 0,
    "pos_ld30k": null,
    "pontos_total": 0,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "Adriana Melo",
    "academia": "PULSE",
    "equipe": "PRO FEMININO",
    "categoria": "Feminino",
    "ftp_final": null,
    "ftp_final_s": null,
    "montanha": null,
    "montanha_s": null,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "01:00:00",
    "ld30k_s": 3600,
    "tempo_total": "01:00:00",
    "tempo_total_s": 3600,
    "provas": 1,
    "completo": false,
    "pontos_ftp": 0,
    "pos_ftp": null,
    "pontos_montanha": 0,
    "pos_montanha": null,
    "pontos_ld30k": 1,
    "pos_ld30k": 11,
    "pontos_total": 1,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "Alê Agra",
    "academia": "PULSE",
    "equipe": "MASTER",
    "categoria": "Feminino",
    "ftp_final": null,
    "ftp_final_s": null,
    "montanha": "00:29:28",
    "montanha_s": 1768,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": "00:29:28",
    "tempo_total_s": 1768,
    "provas": 1,
    "completo": false,
    "pontos_ftp": 0,
    "pos_ftp": null,
    "pontos_montanha": 0,
    "pos_montanha": 13,
    "pontos_ld30k": 0,
    "pos_ld30k": null,
    "pontos_total": 0,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "Allan Oliveira",
    "academia": "AABB",
    "equipe": "SUB-26",
    "categoria": "Masculino",
    "ftp_final": null,
    "ftp_final_s": null,
    "montanha": "00:27:41",
    "montanha_s": 1661,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:52:17",
    "ld30k_s": 3137,
    "tempo_total": "01:19:58",
    "tempo_total_s": 4798,
    "provas": 2,
    "completo": false,
    "pontos_ftp": 0,
    "pos_ftp": null,
    "pontos_montanha": 11,
    "pos_montanha": 6,
    "pontos_ld30k": 5,
    "pos_ld30k": 9,
    "pontos_total": 16,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "Alzinalia Lopes",
    "academia": "BT NS",
    "equipe": "MASTER",
    "categoria": "Feminino",
    "ftp_final": null,
    "ftp_final_s": null,
    "montanha": "00:29:10",
    "montanha_s": 1750,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": "00:29:10",
    "tempo_total_s": 1750,
    "provas": 1,
    "completo": false,
    "pontos_ftp": 0,
    "pos_ftp": null,
    "pontos_montanha": 1,
    "pos_montanha": 11,
    "pontos_ld30k": 0,
    "pos_ld30k": null,
    "pontos_total": 1,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "Sanzia Melo",
    "academia": "BT TIROL",
    "equipe": "MASTER",
    "categoria": "Feminino",
    "ftp_final": null,
    "ftp_final_s": null,
    "montanha": "00:31:09",
    "montanha_s": 1869,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": "00:31:09",
    "tempo_total_s": 1869,
    "provas": 1,
    "completo": false,
    "pontos_ftp": 0,
    "pos_ftp": null,
    "pontos_montanha": 0,
    "pos_montanha": 16,
    "pontos_ld30k": 0,
    "pos_ld30k": null,
    "pontos_total": 0,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "André Fernandes",
    "academia": "BT TIROL",
    "equipe": "MASTER",
    "categoria": "Masculino",
    "ftp_final": null,
    "ftp_final_s": null,
    "montanha": "00:25:13",
    "montanha_s": 1513,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": "00:25:13",
    "tempo_total_s": 1513,
    "provas": 1,
    "completo": false,
    "pontos_ftp": 0,
    "pos_ftp": null,
    "pontos_montanha": 15,
    "pos_montanha": 4,
    "pontos_ld30k": 0,
    "pos_ld30k": null,
    "pontos_total": 15,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "Cris Diniz",
    "academia": "PULSE",
    "equipe": "ELITE FEMININO",
    "categoria": "Feminino",
    "ftp_final": null,
    "ftp_final_s": null,
    "montanha": "00:25:22",
    "montanha_s": 1522,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:46:45",
    "ld30k_s": 2805,
    "tempo_total": "01:12:07",
    "tempo_total_s": 4327,
    "provas": 2,
    "completo": false,
    "pontos_ftp": 0,
    "pos_ftp": null,
    "pontos_montanha": 25,
    "pos_montanha": 1,
    "pontos_ld30k": 25,
    "pos_ld30k": 1,
    "pontos_total": 50,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "Dani Doria",
    "academia": "BT TIROL",
    "equipe": "ELITE FEMININO",
    "categoria": "Feminino",
    "ftp_final": null,
    "ftp_final_s": null,
    "montanha": null,
    "montanha_s": null,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": null,
    "tempo_total_s": null,
    "provas": 0,
    "completo": false,
    "pontos_ftp": 0,
    "pos_ftp": null,
    "pontos_montanha": 0,
    "pos_montanha": null,
    "pontos_ld30k": 0,
    "pos_ld30k": null,
    "pontos_total": 0,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "Gabi Pereira",
    "academia": "PULSE",
    "equipe": "PRO FEMININO",
    "categoria": "Feminino",
    "ftp_final": null,
    "ftp_final_s": null,
    "montanha": null,
    "montanha_s": null,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": null,
    "tempo_total_s": null,
    "provas": 0,
    "completo": false,
    "pontos_ftp": 0,
    "pos_ftp": null,
    "pontos_montanha": 0,
    "pos_montanha": null,
    "pontos_ld30k": 0,
    "pos_ld30k": null,
    "pontos_total": 0,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "Isabel Lucena",
    "academia": "BT TIROL",
    "equipe": "SUB-26",
    "categoria": "Feminino",
    "ftp_final": null,
    "ftp_final_s": null,
    "montanha": "00:30:05",
    "montanha_s": 1805,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:56:34",
    "ld30k_s": 3394,
    "tempo_total": "01:26:39",
    "tempo_total_s": 5199,
    "provas": 2,
    "completo": false,
    "pontos_ftp": 0,
    "pos_ftp": null,
    "pontos_montanha": 0,
    "pos_montanha": 12,
    "pontos_ld30k": 0,
    "pos_ld30k": 13,
    "pontos_total": 0,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "Arthur Martins",
    "academia": "BT NS",
    "equipe": "MASTER",
    "categoria": "Masculino",
    "ftp_final": null,
    "ftp_final_s": null,
    "montanha": "00:23:29",
    "montanha_s": 1409,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:44:34",
    "ld30k_s": 2674,
    "tempo_total": "01:08:03",
    "tempo_total_s": 4083,
    "provas": 2,
    "completo": false,
    "pontos_ftp": 0,
    "pos_ftp": null,
    "pontos_montanha": 25,
    "pos_montanha": 1,
    "pontos_ld30k": 20,
    "pos_ld30k": 2,
    "pontos_total": 45,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "Lia",
    "academia": "BT NS",
    "equipe": "MASTER",
    "categoria": "Feminino",
    "ftp_final": null,
    "ftp_final_s": null,
    "montanha": null,
    "montanha_s": null,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": null,
    "tempo_total_s": null,
    "provas": 0,
    "completo": false,
    "pontos_ftp": 0,
    "pos_ftp": null,
    "pontos_montanha": 0,
    "pos_montanha": null,
    "pontos_ld30k": 0,
    "pos_ld30k": null,
    "pontos_total": 0,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "Lívia Revoredo",
    "academia": "BT NS",
    "equipe": "PRO FEMININO",
    "categoria": "Feminino",
    "ftp_final": null,
    "ftp_final_s": null,
    "montanha": "00:26:47",
    "montanha_s": 1607,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:49:22",
    "ld30k_s": 2962,
    "tempo_total": "01:16:09",
    "tempo_total_s": 4569,
    "provas": 2,
    "completo": false,
    "pontos_ftp": 0,
    "pos_ftp": null,
    "pontos_montanha": 25,
    "pos_montanha": 1,
    "pontos_ld30k": 25,
    "pos_ld30k": 1,
    "pontos_total": 50,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "Bruno Vinicius",
    "academia": "BT TIROL",
    "equipe": "PRO MASCULINO",
    "categoria": "Masculino",
    "ftp_final": null,
    "ftp_final_s": null,
    "montanha": null,
    "montanha_s": null,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": null,
    "tempo_total_s": null,
    "provas": 0,
    "completo": false,
    "pontos_ftp": 0,
    "pos_ftp": null,
    "pontos_montanha": 0,
    "pos_montanha": null,
    "pontos_ld30k": 0,
    "pos_ld30k": null,
    "pontos_total": 0,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "César Britto",
    "academia": "AABB",
    "equipe": "MASTER",
    "categoria": "Masculino",
    "ftp_final": null,
    "ftp_final_s": null,
    "montanha": "00:25:20",
    "montanha_s": 1520,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:47:06",
    "ld30k_s": 2826,
    "tempo_total": "01:12:26",
    "tempo_total_s": 4346,
    "provas": 2,
    "completo": false,
    "pontos_ftp": 0,
    "pos_ftp": null,
    "pontos_montanha": 11,
    "pos_montanha": 6,
    "pontos_ld30k": 15,
    "pos_ld30k": 4,
    "pontos_total": 26,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "Daniel Azevedo",
    "academia": "BT NS",
    "equipe": "ELITE MASCULINO",
    "categoria": "Masculino",
    "ftp_final": null,
    "ftp_final_s": null,
    "montanha": "00:25:42",
    "montanha_s": 1542,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:44:27",
    "ld30k_s": 2667,
    "tempo_total": "01:10:09",
    "tempo_total_s": 4209,
    "provas": 2,
    "completo": false,
    "pontos_ftp": 0,
    "pos_ftp": null,
    "pontos_montanha": 0,
    "pos_montanha": 13,
    "pontos_ld30k": 11,
    "pos_ld30k": 6,
    "pontos_total": 11,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "Daniel Freire",
    "academia": "PULSE",
    "equipe": "MASTER",
    "categoria": "Masculino",
    "ftp_final": null,
    "ftp_final_s": null,
    "montanha": "00:25:09",
    "montanha_s": 1509,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": "00:25:09",
    "tempo_total_s": 1509,
    "provas": 1,
    "completo": false,
    "pontos_ftp": 0,
    "pos_ftp": null,
    "pontos_montanha": 17,
    "pos_montanha": 3,
    "pontos_ld30k": 0,
    "pos_ld30k": null,
    "pontos_total": 17,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "Lydia Tinôco",
    "academia": "AABB",
    "equipe": "ELITE FEMININO",
    "categoria": "Feminino",
    "ftp_final": null,
    "ftp_final_s": null,
    "montanha": "00:28:16",
    "montanha_s": 1696,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:53:31",
    "ld30k_s": 3211,
    "tempo_total": "01:21:47",
    "tempo_total_s": 4907,
    "provas": 2,
    "completo": false,
    "pontos_ftp": 0,
    "pos_ftp": null,
    "pontos_montanha": 1,
    "pos_montanha": 11,
    "pontos_ld30k": 0,
    "pos_ld30k": 12,
    "pontos_total": 1,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "Elistenio Filho",
    "academia": "BT TIROL",
    "equipe": "SUB-26",
    "categoria": "Masculino",
    "ftp_final": null,
    "ftp_final_s": null,
    "montanha": "00:30:06",
    "montanha_s": 1806,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": "00:30:06",
    "tempo_total_s": 1806,
    "provas": 1,
    "completo": false,
    "pontos_ftp": 0,
    "pos_ftp": null,
    "pontos_montanha": 0,
    "pos_montanha": 13,
    "pontos_ld30k": 0,
    "pos_ld30k": null,
    "pontos_total": 0,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "Francisco Vito",
    "academia": "PULSE",
    "equipe": "SUB-26",
    "categoria": "Masculino",
    "ftp_final": null,
    "ftp_final_s": null,
    "montanha": "00:26:53",
    "montanha_s": 1613,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": "00:26:53",
    "tempo_total_s": 1613,
    "provas": 1,
    "completo": false,
    "pontos_ftp": 0,
    "pos_ftp": null,
    "pontos_montanha": 13,
    "pos_montanha": 5,
    "pontos_ld30k": 0,
    "pos_ld30k": null,
    "pontos_total": 13,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "Haroldo Duarte",
    "academia": "AABB",
    "equipe": "PRO MASCULINO",
    "categoria": "Masculino",
    "ftp_final": null,
    "ftp_final_s": null,
    "montanha": "00:25:11",
    "montanha_s": 1511,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:47:58",
    "ld30k_s": 2878,
    "tempo_total": "01:13:09",
    "tempo_total_s": 4389,
    "provas": 2,
    "completo": false,
    "pontos_ftp": 0,
    "pos_ftp": null,
    "pontos_montanha": 11,
    "pos_montanha": 6,
    "pontos_ld30k": 11,
    "pos_ld30k": 6,
    "pontos_total": 22,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "Igor Rosado",
    "academia": "BT TIROL",
    "equipe": "PRO MASCULINO",
    "categoria": "Masculino",
    "ftp_final": null,
    "ftp_final_s": null,
    "montanha": "00:28:19",
    "montanha_s": 1699,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": "00:28:19",
    "tempo_total_s": 1699,
    "provas": 1,
    "completo": false,
    "pontos_ftp": 0,
    "pos_ftp": null,
    "pontos_montanha": 1,
    "pos_montanha": 11,
    "pontos_ld30k": 0,
    "pos_ld30k": null,
    "pontos_total": 1,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "Raissa Georgia",
    "academia": "BT TIROL",
    "equipe": "ELITE FEMININO",
    "categoria": "Feminino",
    "ftp_final": null,
    "ftp_final_s": null,
    "montanha": "00:26:57",
    "montanha_s": 1617,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:50:44",
    "ld30k_s": 3044,
    "tempo_total": "01:17:41",
    "tempo_total_s": 4661,
    "provas": 2,
    "completo": false,
    "pontos_ftp": 0,
    "pos_ftp": null,
    "pontos_montanha": 9,
    "pos_montanha": 7,
    "pontos_ld30k": 5,
    "pos_ld30k": 9,
    "pontos_total": 14,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "Jair",
    "academia": "BT NS",
    "equipe": "PRO MASCULINO",
    "categoria": "Masculino",
    "ftp_final": null,
    "ftp_final_s": null,
    "montanha": null,
    "montanha_s": null,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": null,
    "tempo_total_s": null,
    "provas": 0,
    "completo": false,
    "pontos_ftp": 0,
    "pos_ftp": null,
    "pontos_montanha": 0,
    "pos_montanha": null,
    "pontos_ld30k": 0,
    "pos_ld30k": null,
    "pontos_total": 0,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "Joao Pedro",
    "academia": "BT NS",
    "equipe": "SUB-26",
    "categoria": "Masculino",
    "ftp_final": null,
    "ftp_final_s": null,
    "montanha": "00:25:02",
    "montanha_s": 1502,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:45:06",
    "ld30k_s": 2706,
    "tempo_total": "01:10:08",
    "tempo_total_s": 4208,
    "provas": 2,
    "completo": false,
    "pontos_ftp": 0,
    "pos_ftp": null,
    "pontos_montanha": 25,
    "pos_montanha": 1,
    "pontos_ld30k": 20,
    "pos_ld30k": 2,
    "pontos_total": 45,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "Samara Silva",
    "academia": "BT NS",
    "equipe": "SUB-26",
    "categoria": "Feminino",
    "ftp_final": null,
    "ftp_final_s": null,
    "montanha": "00:30:54",
    "montanha_s": 1854,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "01:00:28",
    "ld30k_s": 3628,
    "tempo_total": "01:31:22",
    "tempo_total_s": 5482,
    "provas": 2,
    "completo": false,
    "pontos_ftp": 0,
    "pos_ftp": null,
    "pontos_montanha": 0,
    "pos_montanha": 14,
    "pontos_ld30k": 0,
    "pos_ld30k": 14,
    "pontos_total": 0,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "Sheila Sales",
    "academia": "AABB",
    "equipe": "MASTER",
    "categoria": "Feminino",
    "ftp_final": null,
    "ftp_final_s": null,
    "montanha": null,
    "montanha_s": null,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:55:38",
    "ld30k_s": 3338,
    "tempo_total": "00:55:38",
    "tempo_total_s": 3338,
    "provas": 1,
    "completo": false,
    "pontos_ftp": 0,
    "pos_ftp": null,
    "pontos_montanha": 0,
    "pos_montanha": null,
    "pontos_ld30k": 0,
    "pos_ld30k": 15,
    "pontos_total": 0,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "Maria J nobrega",
    "academia": "BT TIROL",
    "equipe": "SUB-26",
    "categoria": "Feminino",
    "ftp_final": null,
    "ftp_final_s": null,
    "montanha": null,
    "montanha_s": null,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:49:01",
    "ld30k_s": 2941,
    "tempo_total": "00:49:01",
    "tempo_total_s": 2941,
    "provas": 2,
    "completo": false,
    "pontos_ftp": 0,
    "pos_ftp": null,
    "pontos_montanha": 0,
    "pos_montanha": null,
    "pontos_ld30k": 11,
    "pos_ld30k": 6,
    "pontos_total": 11,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "CLAUDIA REGINA",
    "academia": "BT TIROL",
    "equipe": "MASTER",
    "categoria": "Feminino",
    "ftp_final": "00:00:16",
    "ftp_final_s": 16,
    "montanha": null,
    "montanha_s": null,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:53:31",
    "ld30k_s": 3211,
    "tempo_total": "00:53:47",
    "tempo_total_s": 3227,
    "provas": 2,
    "completo": false,
    "pontos_ftp": 9,
    "pos_ftp": 7,
    "pontos_montanha": 0,
    "pos_montanha": null,
    "pontos_ld30k": 0,
    "pos_ld30k": 12,
    "pontos_total": 9,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "Simone Ribeiro",
    "academia": "BT NS",
    "equipe": "ELITE FEMININO",
    "categoria": "Feminino",
    "ftp_final": "00:00:04",
    "ftp_final_s": 4,
    "montanha": "00:26:23",
    "montanha_s": 1583,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:48:05",
    "ld30k_s": 2885,
    "tempo_total": "01:14:32",
    "tempo_total_s": 4472,
    "provas": 3,
    "completo": true,
    "pontos_ftp": 25,
    "pos_ftp": 1,
    "pontos_montanha": 15,
    "pos_montanha": 4,
    "pontos_ld30k": 17,
    "pos_ld30k": 3,
    "pontos_total": 57,
    "pos_geral": 1,
    "pos_geral_categoria": 1
  },
  {
    "atleta": "Kleber Gentil",
    "academia": "BT NS",
    "equipe": "PRO MASCULINO",
    "categoria": "Masculino",
    "ftp_final": null,
    "ftp_final_s": null,
    "montanha": "00:26:13",
    "montanha_s": 1573,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:53:13",
    "ld30k_s": 3193,
    "tempo_total": "01:19:26",
    "tempo_total_s": 4766,
    "provas": 2,
    "completo": false,
    "pontos_ftp": 0,
    "pos_ftp": null,
    "pontos_montanha": 5,
    "pos_montanha": 9,
    "pontos_ld30k": 5,
    "pos_ld30k": 9,
    "pontos_total": 10,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "Luiz Marcelo",
    "academia": "PULSE",
    "equipe": "PRO MASCULINO",
    "categoria": "Masculino",
    "ftp_final": null,
    "ftp_final_s": null,
    "montanha": null,
    "montanha_s": null,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:48:29",
    "ld30k_s": 2909,
    "tempo_total": "00:48:29",
    "tempo_total_s": 2909,
    "provas": 1,
    "completo": false,
    "pontos_ftp": 0,
    "pos_ftp": null,
    "pontos_montanha": 0,
    "pos_montanha": null,
    "pontos_ld30k": 7,
    "pos_ld30k": 8,
    "pontos_total": 7,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "Rafael Povoas",
    "academia": "PULSE",
    "equipe": "ELITE MASCULINO",
    "categoria": "Masculino",
    "ftp_final": null,
    "ftp_final_s": null,
    "montanha": "00:24:43",
    "montanha_s": 1483,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:45:56",
    "ld30k_s": 2756,
    "tempo_total": "01:10:39",
    "tempo_total_s": 4239,
    "provas": 2,
    "completo": false,
    "pontos_ftp": 0,
    "pos_ftp": null,
    "pontos_montanha": 3,
    "pos_montanha": 10,
    "pontos_ld30k": 3,
    "pos_ld30k": 10,
    "pontos_total": 6,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "Sivonaldo Tercio",
    "academia": "AABB",
    "equipe": "ELITE MASCULINO",
    "categoria": "Masculino",
    "ftp_final": null,
    "ftp_final_s": null,
    "montanha": "00:22:30",
    "montanha_s": 1350,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:42:34",
    "ld30k_s": 2554,
    "tempo_total": "01:05:04",
    "tempo_total_s": 3904,
    "provas": 2,
    "completo": false,
    "pontos_ftp": 0,
    "pos_ftp": null,
    "pontos_montanha": 25,
    "pos_montanha": 1,
    "pontos_ld30k": 15,
    "pos_ld30k": 4,
    "pontos_total": 40,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "Omar Dantas",
    "academia": "BT NS",
    "equipe": "ELITE MASCULINO",
    "categoria": "Masculino",
    "ftp_final": "00:00:13",
    "ftp_final_s": 13,
    "montanha": "00:22:45",
    "montanha_s": 1365,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:41:42",
    "ld30k_s": 2502,
    "tempo_total": "01:04:40",
    "tempo_total_s": 3880,
    "provas": 3,
    "completo": true,
    "pontos_ftp": 7,
    "pos_ftp": 8,
    "pontos_montanha": 20,
    "pos_montanha": 2,
    "pontos_ld30k": 25,
    "pos_ld30k": 1,
    "pontos_total": 52,
    "pos_geral": 1,
    "pos_geral_categoria": 1
  },
  {
    "atleta": "Sergio Torralba",
    "academia": "BT TIROL",
    "equipe": "ELITE MASCULINO",
    "categoria": "Masculino",
    "ftp_final": "00:00:03",
    "ftp_final_s": 3,
    "montanha": "00:23:04",
    "montanha_s": 1384,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:41:55",
    "ld30k_s": 2515,
    "tempo_total": "01:05:02",
    "tempo_total_s": 3902,
    "provas": 3,
    "completo": true,
    "pontos_ftp": 25,
    "pos_ftp": 1,
    "pontos_montanha": 15,
    "pos_montanha": 4,
    "pontos_ld30k": 17,
    "pos_ld30k": 3,
    "pontos_total": 57,
    "pos_geral": 2,
    "pos_geral_categoria": 2
  },
  {
    "atleta": "Diogo Almeida",
    "academia": "PULSE",
    "equipe": "ELITE MASCULINO",
    "categoria": "Masculino",
    "ftp_final": "00:00:05",
    "ftp_final_s": 5,
    "montanha": "00:24:09",
    "montanha_s": 1449,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": "00:24:14",
    "tempo_total_s": 1454,
    "provas": 2,
    "completo": false,
    "pontos_ftp": 20,
    "pos_ftp": 2,
    "pontos_montanha": 5,
    "pos_montanha": 9,
    "pontos_ld30k": 0,
    "pos_ld30k": null,
    "pontos_total": 25,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "Elionai",
    "academia": "PULSE",
    "equipe": "ELITE MASCULINO",
    "categoria": "Masculino",
    "ftp_final": "00:00:07",
    "ftp_final_s": 7,
    "montanha": null,
    "montanha_s": null,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:41:53",
    "ld30k_s": 2513,
    "tempo_total": "00:42:00",
    "tempo_total_s": 2520,
    "provas": 2,
    "completo": false,
    "pontos_ftp": 17,
    "pos_ftp": 3,
    "pontos_montanha": 0,
    "pos_montanha": null,
    "pontos_ld30k": 20,
    "pos_ld30k": 2,
    "pontos_total": 37,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "Bruno Cabral",
    "academia": "AABB",
    "equipe": "PRO MASCULINO",
    "categoria": "Masculino",
    "ftp_final": "00:00:09",
    "ftp_final_s": 9,
    "montanha": "00:24:33",
    "montanha_s": 1473,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": "00:24:42",
    "tempo_total_s": 1482,
    "provas": 2,
    "completo": false,
    "pontos_ftp": 25,
    "pos_ftp": 1,
    "pontos_montanha": 25,
    "pos_montanha": 1,
    "pontos_ld30k": 0,
    "pos_ld30k": null,
    "pontos_total": 50,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "Arthur Dantas",
    "academia": "PULSE",
    "equipe": "PRO MASCULINO",
    "categoria": "Masculino",
    "ftp_final": "00:00:10",
    "ftp_final_s": 10,
    "montanha": "00:24:42",
    "montanha_s": 1482,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": "00:24:52",
    "tempo_total_s": 1492,
    "provas": 2,
    "completo": false,
    "pontos_ftp": 20,
    "pos_ftp": 2,
    "pontos_montanha": 20,
    "pos_montanha": 2,
    "pontos_ld30k": 0,
    "pos_ld30k": null,
    "pontos_total": 40,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "Carlos Thompson",
    "academia": "BT TIROL",
    "equipe": "PRO MASCULINO",
    "categoria": "Masculino",
    "ftp_final": "00:00:10",
    "ftp_final_s": 10,
    "montanha": "00:26:00",
    "montanha_s": 1560,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": "00:26:10",
    "tempo_total_s": 1570,
    "provas": 2,
    "completo": false,
    "pontos_ftp": 17,
    "pos_ftp": 3,
    "pontos_montanha": 7,
    "pos_montanha": 8,
    "pontos_ld30k": 0,
    "pos_ld30k": null,
    "pontos_total": 24,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "Heloisa Lopes",
    "academia": "BT TIROL",
    "equipe": "PRO FEMININO",
    "categoria": "Feminino",
    "ftp_final": "00:00:09",
    "ftp_final_s": 9,
    "montanha": null,
    "montanha_s": null,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:53:42",
    "ld30k_s": 3222,
    "tempo_total": "00:53:51",
    "tempo_total_s": 3231,
    "provas": 2,
    "completo": false,
    "pontos_ftp": 25,
    "pos_ftp": 1,
    "pontos_montanha": 0,
    "pos_montanha": null,
    "pontos_ld30k": 7,
    "pos_ld30k": 8,
    "pontos_total": 32,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "LIEGE",
    "academia": "PULSE",
    "equipe": "MASTER",
    "categoria": "Feminino",
    "ftp_final": "00:00:09",
    "ftp_final_s": 9,
    "montanha": null,
    "montanha_s": null,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:50:14",
    "ld30k_s": 3014,
    "tempo_total": "00:50:23",
    "tempo_total_s": 3023,
    "provas": 2,
    "completo": false,
    "pontos_ftp": 25,
    "pos_ftp": 1,
    "pontos_montanha": 0,
    "pos_montanha": null,
    "pontos_ld30k": 7,
    "pos_ld30k": 8,
    "pontos_total": 32,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "Lucas Leonardo",
    "academia": "PULSE",
    "equipe": "ELITE MASCULINO",
    "categoria": "Masculino",
    "ftp_final": "00:00:12",
    "ftp_final_s": 12,
    "montanha": "00:22:47",
    "montanha_s": 1367,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:42:57",
    "ld30k_s": 2577,
    "tempo_total": "01:05:56",
    "tempo_total_s": 3956,
    "provas": 3,
    "completo": true,
    "pontos_ftp": 9,
    "pos_ftp": 7,
    "pontos_montanha": 17,
    "pos_montanha": 3,
    "pontos_ld30k": 13,
    "pos_ld30k": 5,
    "pontos_total": 39,
    "pos_geral": 3,
    "pos_geral_categoria": 3
  },
  {
    "atleta": "Andréia Medeiros",
    "academia": "BT TIROL",
    "equipe": "ELITE FEMININO",
    "categoria": "Feminino",
    "ftp_final": "00:00:11",
    "ftp_final_s": 11,
    "montanha": "00:26:19",
    "montanha_s": 1579,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:48:16",
    "ld30k_s": 2896,
    "tempo_total": "01:14:46",
    "tempo_total_s": 4486,
    "provas": 3,
    "completo": true,
    "pontos_ftp": 15,
    "pos_ftp": 4,
    "pontos_montanha": 17,
    "pos_montanha": 3,
    "pontos_ld30k": 15,
    "pos_ld30k": 4,
    "pontos_total": 47,
    "pos_geral": 2,
    "pos_geral_categoria": 2
  },
  {
    "atleta": "Neto Xavier",
    "academia": "BT NS",
    "equipe": "ELITE MASCULINO",
    "categoria": "Masculino",
    "ftp_final": null,
    "ftp_final_s": null,
    "montanha": "00:23:38",
    "montanha_s": 1418,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:44:32",
    "ld30k_s": 2672,
    "tempo_total": "01:08:10",
    "tempo_total_s": 4090,
    "provas": 3,
    "completo": true,
    "pontos_ftp": 0,
    "pos_ftp": null,
    "pontos_montanha": 11,
    "pos_montanha": 6,
    "pontos_ld30k": 5,
    "pos_ld30k": 9,
    "pontos_total": 16,
    "pos_geral": 4,
    "pos_geral_categoria": 4
  },
  {
    "atleta": "Alini Brito",
    "academia": "BT NS",
    "equipe": "ELITE FEMININO",
    "categoria": "Feminino",
    "ftp_final": "00:00:10",
    "ftp_final_s": 10,
    "montanha": "00:26:18",
    "montanha_s": 1578,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:48:31",
    "ld30k_s": 2911,
    "tempo_total": "01:14:59",
    "tempo_total_s": 4499,
    "provas": 3,
    "completo": true,
    "pontos_ftp": 17,
    "pos_ftp": 3,
    "pontos_montanha": 20,
    "pos_montanha": 2,
    "pontos_ld30k": 13,
    "pos_ld30k": 5,
    "pontos_total": 50,
    "pos_geral": 3,
    "pos_geral_categoria": 3
  },
  {
    "atleta": "Joyce Ribeiro",
    "academia": "BT NS",
    "equipe": "ELITE FEMININO",
    "categoria": "Feminino",
    "ftp_final": "00:00:11",
    "ftp_final_s": 11,
    "montanha": "00:26:54",
    "montanha_s": 1614,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:48:01",
    "ld30k_s": 2881,
    "tempo_total": "01:15:06",
    "tempo_total_s": 4506,
    "provas": 3,
    "completo": true,
    "pontos_ftp": 13,
    "pos_ftp": 5,
    "pontos_montanha": 11,
    "pos_montanha": 6,
    "pontos_ld30k": 20,
    "pos_ld30k": 2,
    "pontos_total": 44,
    "pos_geral": 4,
    "pos_geral_categoria": 4
  },
  {
    "atleta": "Renata Seixas",
    "academia": "BT TIROL",
    "equipe": "ELITE FEMININO",
    "categoria": "Feminino",
    "ftp_final": "00:00:17",
    "ftp_final_s": 17,
    "montanha": "00:26:45",
    "montanha_s": 1605,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:49:42",
    "ld30k_s": 2982,
    "tempo_total": "01:16:44",
    "tempo_total_s": 4604,
    "provas": 3,
    "completo": true,
    "pontos_ftp": 1,
    "pos_ftp": 11,
    "pontos_montanha": 13,
    "pos_montanha": 5,
    "pontos_ld30k": 9,
    "pos_ld30k": 7,
    "pontos_total": 23,
    "pos_geral": 5,
    "pos_geral_categoria": 5
  },
  {
    "atleta": "Bira Carratu",
    "academia": "AABB",
    "equipe": "ELITE MASCULINO",
    "categoria": "Masculino",
    "ftp_final": "00:00:11",
    "ftp_final_s": 11,
    "montanha": "00:23:39",
    "montanha_s": 1419,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": "00:23:50",
    "tempo_total_s": 1430,
    "provas": 2,
    "completo": false,
    "pontos_ftp": 15,
    "pos_ftp": 4,
    "pontos_montanha": 9,
    "pos_montanha": 7,
    "pontos_ld30k": 0,
    "pos_ld30k": null,
    "pontos_total": 24,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "Raimundo Romão",
    "academia": "BT NS",
    "equipe": "MASTER",
    "categoria": "Masculino",
    "ftp_final": "00:00:11",
    "ftp_final_s": 11,
    "montanha": null,
    "montanha_s": null,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:43:44",
    "ld30k_s": 2624,
    "tempo_total": "00:43:55",
    "tempo_total_s": 2635,
    "provas": 2,
    "completo": false,
    "pontos_ftp": 20,
    "pos_ftp": 2,
    "pontos_montanha": 0,
    "pos_montanha": null,
    "pontos_ld30k": 25,
    "pos_ld30k": 1,
    "pontos_total": 45,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "Jannaina Queiroz",
    "academia": "BT TIROL",
    "equipe": "ELITE FEMININO",
    "categoria": "Feminino",
    "ftp_final": "00:00:11",
    "ftp_final_s": 11,
    "montanha": null,
    "montanha_s": null,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": "00:00:11",
    "tempo_total_s": 11,
    "provas": 1,
    "completo": false,
    "pontos_ftp": 11,
    "pos_ftp": 6,
    "pontos_montanha": 0,
    "pos_montanha": null,
    "pontos_ld30k": 0,
    "pos_ld30k": null,
    "pontos_total": 11,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "Silvia Drummond",
    "academia": "AABB",
    "equipe": "ELITE FEMININO",
    "categoria": "Feminino",
    "ftp_final": "00:00:11",
    "ftp_final_s": 11,
    "montanha": "00:27:54",
    "montanha_s": 1674,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:48:55",
    "ld30k_s": 2935,
    "tempo_total": "01:17:00",
    "tempo_total_s": 4620,
    "provas": 3,
    "completo": true,
    "pontos_ftp": 9,
    "pos_ftp": 7,
    "pontos_montanha": 5,
    "pos_montanha": 9,
    "pontos_ld30k": 11,
    "pos_ld30k": 6,
    "pontos_total": 25,
    "pos_geral": 6,
    "pos_geral_categoria": 6
  },
  {
    "atleta": "Sarah Brito",
    "academia": "AABB",
    "equipe": "ELITE FEMININO",
    "categoria": "Feminino",
    "ftp_final": "00:00:09",
    "ftp_final_s": 9,
    "montanha": "00:27:10",
    "montanha_s": 1630,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:49:48",
    "ld30k_s": 2988,
    "tempo_total": "01:17:07",
    "tempo_total_s": 4627,
    "provas": 3,
    "completo": true,
    "pontos_ftp": 20,
    "pos_ftp": 2,
    "pontos_montanha": 7,
    "pos_montanha": 8,
    "pontos_ld30k": 7,
    "pos_ld30k": 8,
    "pontos_total": 34,
    "pos_geral": 7,
    "pos_geral_categoria": 7
  },
  {
    "atleta": "Renato Araújo",
    "academia": "AABB",
    "equipe": "ELITE MASCULINO",
    "categoria": "Masculino",
    "ftp_final": "00:00:11",
    "ftp_final_s": 11,
    "montanha": null,
    "montanha_s": null,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:48:12",
    "ld30k_s": 2892,
    "tempo_total": "00:48:23",
    "tempo_total_s": 2903,
    "provas": 2,
    "completo": false,
    "pontos_ftp": 13,
    "pos_ftp": 5,
    "pontos_montanha": 0,
    "pos_montanha": null,
    "pontos_ld30k": 0,
    "pos_ld30k": 12,
    "pontos_total": 13,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "Andreia Araujo",
    "academia": "BT TIROL",
    "equipe": "PRO FEMININO",
    "categoria": "Feminino",
    "ftp_final": "00:00:21",
    "ftp_final_s": 21,
    "montanha": "00:27:33",
    "montanha_s": 1653,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:52:24",
    "ld30k_s": 3144,
    "tempo_total": "01:20:18",
    "tempo_total_s": 4818,
    "provas": 3,
    "completo": true,
    "pontos_ftp": 1,
    "pos_ftp": 11,
    "pontos_montanha": 20,
    "pos_montanha": 2,
    "pontos_ld30k": 20,
    "pos_ld30k": 2,
    "pontos_total": 41,
    "pos_geral": 8,
    "pos_geral_categoria": 1
  },
  {
    "atleta": "Hívila Moreira",
    "academia": "PULSE",
    "equipe": "ELITE FEMININO",
    "categoria": "Feminino",
    "ftp_final": "00:00:14",
    "ftp_final_s": 14,
    "montanha": "00:28:02",
    "montanha_s": 1682,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:52:39",
    "ld30k_s": 3159,
    "tempo_total": "01:20:55",
    "tempo_total_s": 4855,
    "provas": 3,
    "completo": true,
    "pontos_ftp": 7,
    "pos_ftp": 8,
    "pontos_montanha": 3,
    "pos_montanha": 10,
    "pontos_ld30k": 1,
    "pos_ld30k": 11,
    "pontos_total": 11,
    "pos_geral": 9,
    "pos_geral_categoria": 8
  },
  {
    "atleta": "Genival Ferreira",
    "academia": "AABB",
    "equipe": "ELITE MASCULINO",
    "categoria": "Masculino",
    "ftp_final": "00:00:11",
    "ftp_final_s": 11,
    "montanha": "00:23:37",
    "montanha_s": 1417,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:44:28",
    "ld30k_s": 2668,
    "tempo_total": "01:08:16",
    "tempo_total_s": 4096,
    "provas": 3,
    "completo": true,
    "pontos_ftp": 11,
    "pos_ftp": 6,
    "pontos_montanha": 13,
    "pos_montanha": 5,
    "pontos_ld30k": 9,
    "pos_ld30k": 7,
    "pontos_total": 33,
    "pos_geral": 5,
    "pos_geral_categoria": 5
  },
  {
    "atleta": "Karine Symonir",
    "academia": "PULSE",
    "equipe": "ELITE FEMININO",
    "categoria": "Feminino",
    "ftp_final": "00:00:15",
    "ftp_final_s": 15,
    "montanha": "00:28:17",
    "montanha_s": 1697,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:52:25",
    "ld30k_s": 3145,
    "tempo_total": "01:20:57",
    "tempo_total_s": 4857,
    "provas": 3,
    "completo": true,
    "pontos_ftp": 3,
    "pos_ftp": 10,
    "pontos_montanha": 0,
    "pos_montanha": 12,
    "pontos_ld30k": 3,
    "pos_ld30k": 10,
    "pontos_total": 6,
    "pos_geral": 10,
    "pos_geral_categoria": 9
  },
  {
    "atleta": "Lucas Eurípides",
    "academia": "BT TIROL",
    "equipe": "SUB-26",
    "categoria": "Masculino",
    "ftp_final": "00:00:17",
    "ftp_final_s": 17,
    "montanha": "00:25:02",
    "montanha_s": 1502,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:44:37",
    "ld30k_s": 2677,
    "tempo_total": "01:09:56",
    "tempo_total_s": 4196,
    "provas": 3,
    "completo": true,
    "pontos_ftp": 9,
    "pos_ftp": 7,
    "pontos_montanha": 20,
    "pos_montanha": 2,
    "pontos_ld30k": 25,
    "pos_ld30k": 1,
    "pontos_total": 54,
    "pos_geral": 6,
    "pos_geral_categoria": 1
  },
  {
    "atleta": "Gringo",
    "academia": "BT NS",
    "equipe": "ELITE MASCULINO",
    "categoria": "Masculino",
    "ftp_final": "00:00:13",
    "ftp_final_s": 13,
    "montanha": "00:25:14",
    "montanha_s": 1514,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": "00:25:27",
    "tempo_total_s": 1527,
    "provas": 2,
    "completo": false,
    "pontos_ftp": 5,
    "pos_ftp": 9,
    "pontos_montanha": 0,
    "pos_montanha": 12,
    "pontos_ld30k": 0,
    "pos_ld30k": null,
    "pontos_total": 5,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "José Wilson",
    "academia": "PULSE",
    "equipe": "SUB-26",
    "categoria": "Masculino",
    "ftp_final": "00:00:13",
    "ftp_final_s": 13,
    "montanha": null,
    "montanha_s": null,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:46:42",
    "ld30k_s": 2802,
    "tempo_total": "00:46:55",
    "tempo_total_s": 2815,
    "provas": 2,
    "completo": false,
    "pontos_ftp": 17,
    "pos_ftp": 3,
    "pontos_montanha": 0,
    "pos_montanha": null,
    "pontos_ld30k": 17,
    "pos_ld30k": 3,
    "pontos_total": 34,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "Olisuel Pereira",
    "academia": "PULSE",
    "equipe": "PRO MASCULINO",
    "categoria": "Masculino",
    "ftp_final": "00:00:14",
    "ftp_final_s": 14,
    "montanha": "00:24:49",
    "montanha_s": 1489,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:45:24",
    "ld30k_s": 2724,
    "tempo_total": "01:10:27",
    "tempo_total_s": 4227,
    "provas": 3,
    "completo": true,
    "pontos_ftp": 13,
    "pos_ftp": 5,
    "pontos_montanha": 13,
    "pos_montanha": 5,
    "pontos_ld30k": 25,
    "pos_ld30k": 1,
    "pontos_total": 51,
    "pos_geral": 7,
    "pos_geral_categoria": 1
  },
  {
    "atleta": "Livia Darc",
    "academia": "BT NS",
    "equipe": "SUB-26",
    "categoria": "Feminino",
    "ftp_final": "00:00:15",
    "ftp_final_s": 15,
    "montanha": "00:29:19",
    "montanha_s": 1759,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:51:51",
    "ld30k_s": 3111,
    "tempo_total": "01:21:25",
    "tempo_total_s": 4885,
    "provas": 3,
    "completo": true,
    "pontos_ftp": 15,
    "pos_ftp": 4,
    "pontos_montanha": 3,
    "pos_montanha": 10,
    "pontos_ld30k": 9,
    "pos_ld30k": 7,
    "pontos_total": 27,
    "pos_geral": 11,
    "pos_geral_categoria": 4
  },
  {
    "atleta": "Camila Mota",
    "academia": "AABB",
    "equipe": "PRO FEMININO",
    "categoria": "Feminino",
    "ftp_final": "00:00:14",
    "ftp_final_s": 14,
    "montanha": "00:28:39",
    "montanha_s": 1719,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:52:47",
    "ld30k_s": 3167,
    "tempo_total": "01:21:40",
    "tempo_total_s": 4900,
    "provas": 3,
    "completo": true,
    "pontos_ftp": 11,
    "pos_ftp": 6,
    "pontos_montanha": 15,
    "pos_montanha": 4,
    "pontos_ld30k": 17,
    "pos_ld30k": 3,
    "pontos_total": 43,
    "pos_geral": 12,
    "pos_geral_categoria": 2
  },
  {
    "atleta": "Beatriz Bezerra",
    "academia": "BT NS",
    "equipe": "PRO FEMININO",
    "categoria": "Feminino",
    "ftp_final": "00:00:13",
    "ftp_final_s": 13,
    "montanha": "00:28:49",
    "montanha_s": 1729,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:52:56",
    "ld30k_s": 3176,
    "tempo_total": "01:21:58",
    "tempo_total_s": 4918,
    "provas": 3,
    "completo": true,
    "pontos_ftp": 13,
    "pos_ftp": 5,
    "pontos_montanha": 11,
    "pos_montanha": 6,
    "pontos_ld30k": 13,
    "pos_ld30k": 5,
    "pontos_total": 37,
    "pos_geral": 13,
    "pos_geral_categoria": 3
  },
  {
    "atleta": "Vanessa Rodrigues",
    "academia": "BT TIROL",
    "equipe": "PRO FEMININO",
    "categoria": "Feminino",
    "ftp_final": "00:00:14",
    "ftp_final_s": 14,
    "montanha": "00:29:36",
    "montanha_s": 1776,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": "00:29:50",
    "tempo_total_s": 1790,
    "provas": 2,
    "completo": false,
    "pontos_ftp": 9,
    "pos_ftp": 7,
    "pontos_montanha": 5,
    "pos_montanha": 9,
    "pontos_ld30k": 0,
    "pos_ld30k": null,
    "pontos_total": 14,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "José Arimatéia",
    "academia": "AABB",
    "equipe": "PRO MASCULINO",
    "categoria": "Masculino",
    "ftp_final": "00:00:11",
    "ftp_final_s": 11,
    "montanha": "00:24:46",
    "montanha_s": 1486,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:46:12",
    "ld30k_s": 2772,
    "tempo_total": "01:11:09",
    "tempo_total_s": 4269,
    "provas": 3,
    "completo": true,
    "pontos_ftp": 15,
    "pos_ftp": 4,
    "pontos_montanha": 15,
    "pos_montanha": 4,
    "pontos_ld30k": 17,
    "pos_ld30k": 3,
    "pontos_total": 47,
    "pos_geral": 8,
    "pos_geral_categoria": 2
  },
  {
    "atleta": "Oona Lopes",
    "academia": "AABB",
    "equipe": "ELITE FEMININO",
    "categoria": "Feminino",
    "ftp_final": "00:00:14",
    "ftp_final_s": 14,
    "montanha": null,
    "montanha_s": null,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": "00:00:14",
    "tempo_total_s": 14,
    "provas": 1,
    "completo": false,
    "pontos_ftp": 5,
    "pos_ftp": 9,
    "pontos_montanha": 0,
    "pos_montanha": null,
    "pontos_ld30k": 0,
    "pos_ld30k": null,
    "pontos_total": 5,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "Socorro Linhares",
    "academia": "BT NS",
    "equipe": "MASTER",
    "categoria": "Feminino",
    "ftp_final": "00:00:14",
    "ftp_final_s": 14,
    "montanha": "00:29:17",
    "montanha_s": 1757,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:52:42",
    "ld30k_s": 3162,
    "tempo_total": "01:22:13",
    "tempo_total_s": 4933,
    "provas": 3,
    "completo": true,
    "pontos_ftp": 15,
    "pos_ftp": 4,
    "pontos_montanha": 0,
    "pos_montanha": 12,
    "pontos_ld30k": 3,
    "pos_ld30k": 10,
    "pontos_total": 18,
    "pos_geral": 14,
    "pos_geral_categoria": 3
  },
  {
    "atleta": "Helena Jales",
    "academia": "AABB",
    "equipe": "PRO FEMININO",
    "categoria": "Feminino",
    "ftp_final": "00:00:14",
    "ftp_final_s": 14,
    "montanha": null,
    "montanha_s": null,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": "00:00:14",
    "tempo_total_s": 14,
    "provas": 1,
    "completo": false,
    "pontos_ftp": 7,
    "pos_ftp": 8,
    "pontos_montanha": 0,
    "pos_montanha": null,
    "pontos_ld30k": 0,
    "pos_ld30k": null,
    "pontos_total": 7,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "Ana Azevedo",
    "academia": "PULSE",
    "equipe": "PRO FEMININO",
    "categoria": "Feminino",
    "ftp_final": "00:00:10",
    "ftp_final_s": 10,
    "montanha": "00:28:44",
    "montanha_s": 1724,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:53:20",
    "ld30k_s": 3200,
    "tempo_total": "01:22:14",
    "tempo_total_s": 4934,
    "provas": 3,
    "completo": true,
    "pontos_ftp": 20,
    "pos_ftp": 2,
    "pontos_montanha": 13,
    "pos_montanha": 5,
    "pontos_ld30k": 9,
    "pos_ld30k": 7,
    "pontos_total": 42,
    "pos_geral": 15,
    "pos_geral_categoria": 4
  },
  {
    "atleta": "Renata Ivia",
    "academia": "BT NS",
    "equipe": "PRO FEMININO",
    "categoria": "Feminino",
    "ftp_final": "00:00:15",
    "ftp_final_s": 15,
    "montanha": null,
    "montanha_s": null,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": "00:00:15",
    "tempo_total_s": 15,
    "provas": 1,
    "completo": false,
    "pontos_ftp": 5,
    "pos_ftp": 9,
    "pontos_montanha": 0,
    "pos_montanha": null,
    "pontos_ld30k": 0,
    "pos_ld30k": null,
    "pontos_total": 5,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "Washington Filho",
    "academia": "BT NS",
    "equipe": "PRO MASCULINO",
    "categoria": "Masculino",
    "ftp_final": "00:00:14",
    "ftp_final_s": 14,
    "montanha": "00:24:44",
    "montanha_s": 1484,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:46:22",
    "ld30k_s": 2782,
    "tempo_total": "01:11:20",
    "tempo_total_s": 4280,
    "provas": 3,
    "completo": true,
    "pontos_ftp": 11,
    "pos_ftp": 6,
    "pontos_montanha": 17,
    "pos_montanha": 3,
    "pontos_ld30k": 13,
    "pos_ld30k": 5,
    "pontos_total": 41,
    "pos_geral": 9,
    "pos_geral_categoria": 3
  },
  {
    "atleta": "Orlando Cunha",
    "academia": "BT TIROL",
    "equipe": "MASTER",
    "categoria": "Masculino",
    "ftp_final": "00:00:16",
    "ftp_final_s": 16,
    "montanha": "00:24:51",
    "montanha_s": 1491,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:46:17",
    "ld30k_s": 2777,
    "tempo_total": "01:11:24",
    "tempo_total_s": 4284,
    "provas": 3,
    "completo": true,
    "pontos_ftp": 7,
    "pos_ftp": 8,
    "pontos_montanha": 20,
    "pos_montanha": 2,
    "pontos_ld30k": 17,
    "pos_ld30k": 3,
    "pontos_total": 44,
    "pos_geral": 10,
    "pos_geral_categoria": 1
  },
  {
    "atleta": "Ana P. Mendes",
    "academia": "BT TIROL",
    "equipe": "MASTER",
    "categoria": "Feminino",
    "ftp_final": "00:00:14",
    "ftp_final_s": 14,
    "montanha": "00:28:43",
    "montanha_s": 1723,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:53:29",
    "ld30k_s": 3209,
    "tempo_total": "01:22:26",
    "tempo_total_s": 4946,
    "provas": 3,
    "completo": true,
    "pontos_ftp": 13,
    "pos_ftp": 5,
    "pontos_montanha": 3,
    "pos_montanha": 10,
    "pontos_ld30k": 1,
    "pos_ld30k": 11,
    "pontos_total": 17,
    "pos_geral": 16,
    "pos_geral_categoria": 4
  },
  {
    "atleta": "Fabrício Barros",
    "academia": "BT TIROL",
    "equipe": "ELITE MASCULINO",
    "categoria": "Masculino",
    "ftp_final": "00:00:17",
    "ftp_final_s": 17,
    "montanha": "00:25:00",
    "montanha_s": 1500,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:46:13",
    "ld30k_s": 2773,
    "tempo_total": "01:11:30",
    "tempo_total_s": 4290,
    "provas": 3,
    "completo": true,
    "pontos_ftp": 3,
    "pos_ftp": 10,
    "pontos_montanha": 1,
    "pos_montanha": 11,
    "pontos_ld30k": 1,
    "pos_ld30k": 11,
    "pontos_total": 5,
    "pos_geral": 11,
    "pos_geral_categoria": 6
  },
  {
    "atleta": "Armando Nóbrega",
    "academia": "AABB",
    "equipe": "MASTER",
    "categoria": "Masculino",
    "ftp_final": "00:00:15",
    "ftp_final_s": 15,
    "montanha": null,
    "montanha_s": null,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:49:22",
    "ld30k_s": 2962,
    "tempo_total": "00:49:37",
    "tempo_total_s": 2977,
    "provas": 2,
    "completo": false,
    "pontos_ftp": 11,
    "pos_ftp": 6,
    "pontos_montanha": 0,
    "pos_montanha": null,
    "pontos_ld30k": 9,
    "pos_ld30k": 7,
    "pontos_total": 20,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "César Maia",
    "academia": "AABB",
    "equipe": "PRO MASCULINO",
    "categoria": "Masculino",
    "ftp_final": "00:00:16",
    "ftp_final_s": 16,
    "montanha": null,
    "montanha_s": null,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:45:50",
    "ld30k_s": 2750,
    "tempo_total": "00:46:06",
    "tempo_total_s": 2766,
    "provas": 2,
    "completo": false,
    "pontos_ftp": 7,
    "pos_ftp": 8,
    "pontos_montanha": 0,
    "pos_montanha": null,
    "pontos_ld30k": 20,
    "pos_ld30k": 2,
    "pontos_total": 27,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "Isadora Meybel",
    "academia": "BT NS",
    "equipe": "PRO FEMININO",
    "categoria": "Feminino",
    "ftp_final": "00:00:11",
    "ftp_final_s": 11,
    "montanha": "00:29:28",
    "montanha_s": 1768,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:52:51",
    "ld30k_s": 3171,
    "tempo_total": "01:22:30",
    "tempo_total_s": 4950,
    "provas": 3,
    "completo": true,
    "pontos_ftp": 17,
    "pos_ftp": 3,
    "pontos_montanha": 7,
    "pos_montanha": 8,
    "pontos_ld30k": 15,
    "pos_ld30k": 4,
    "pontos_total": 39,
    "pos_geral": 17,
    "pos_geral_categoria": 5
  },
  {
    "atleta": "Allyne França",
    "academia": "AABB",
    "equipe": "PRO FEMININO",
    "categoria": "Feminino",
    "ftp_final": "00:00:12",
    "ftp_final_s": 12,
    "montanha": "00:29:15",
    "montanha_s": 1755,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:53:07",
    "ld30k_s": 3187,
    "tempo_total": "01:22:34",
    "tempo_total_s": 4954,
    "provas": 3,
    "completo": true,
    "pontos_ftp": 15,
    "pos_ftp": 4,
    "pontos_montanha": 9,
    "pos_montanha": 7,
    "pontos_ld30k": 11,
    "pos_ld30k": 6,
    "pontos_total": 35,
    "pos_geral": 18,
    "pos_geral_categoria": 6
  },
  {
    "atleta": "Júlia Rocha",
    "academia": "PULSE",
    "equipe": "SUB-26",
    "categoria": "Feminino",
    "ftp_final": "00:00:10",
    "ftp_final_s": 10,
    "montanha": "00:28:40",
    "montanha_s": 1720,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:54:17",
    "ld30k_s": 3257,
    "tempo_total": "01:23:07",
    "tempo_total_s": 4987,
    "provas": 3,
    "completo": true,
    "pontos_ftp": 25,
    "pos_ftp": 1,
    "pontos_montanha": 5,
    "pos_montanha": 9,
    "pontos_ld30k": 1,
    "pos_ld30k": 11,
    "pontos_total": 31,
    "pos_geral": 19,
    "pos_geral_categoria": 5
  },
  {
    "atleta": "Luna Melo",
    "academia": "BT TIROL",
    "equipe": "SUB-26",
    "categoria": "Feminino",
    "ftp_final": "00:00:17",
    "ftp_final_s": 17,
    "montanha": "00:31:36",
    "montanha_s": 1896,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": "00:31:53",
    "tempo_total_s": 1913,
    "provas": 2,
    "completo": false,
    "pontos_ftp": 7,
    "pos_ftp": 8,
    "pontos_montanha": 0,
    "pos_montanha": 15,
    "pontos_ld30k": 0,
    "pos_ld30k": null,
    "pontos_total": 7,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "Duduzinho",
    "academia": "BT TIROL",
    "equipe": "SUB-26",
    "categoria": "Masculino",
    "ftp_final": "00:00:16",
    "ftp_final_s": 16,
    "montanha": null,
    "montanha_s": null,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "01:01:48",
    "ld30k_s": 3708,
    "tempo_total": "01:02:04",
    "tempo_total_s": 3724,
    "provas": 2,
    "completo": false,
    "pontos_ftp": 11,
    "pos_ftp": 6,
    "pontos_montanha": 0,
    "pos_montanha": null,
    "pontos_ld30k": 0,
    "pos_ld30k": 15,
    "pontos_total": 11,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "Edu Silva",
    "academia": "BT NS",
    "equipe": "PRO MASCULINO",
    "categoria": "Masculino",
    "ftp_final": "00:00:16",
    "ftp_final_s": 16,
    "montanha": null,
    "montanha_s": null,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:46:17",
    "ld30k_s": 2777,
    "tempo_total": "00:46:33",
    "tempo_total_s": 2793,
    "provas": 2,
    "completo": false,
    "pontos_ftp": 5,
    "pos_ftp": 9,
    "pontos_montanha": 0,
    "pos_montanha": null,
    "pontos_ld30k": 15,
    "pos_ld30k": 4,
    "pontos_total": 20,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "Victor Barbosa",
    "academia": "PULSE",
    "equipe": "SUB-26",
    "categoria": "Masculino",
    "ftp_final": "00:00:15",
    "ftp_final_s": 15,
    "montanha": "00:25:16",
    "montanha_s": 1516,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:48:10",
    "ld30k_s": 2890,
    "tempo_total": "01:13:41",
    "tempo_total_s": 4421,
    "provas": 3,
    "completo": true,
    "pontos_ftp": 13,
    "pos_ftp": 5,
    "pontos_montanha": 17,
    "pos_montanha": 3,
    "pontos_ld30k": 15,
    "pos_ld30k": 4,
    "pontos_total": 45,
    "pos_geral": 12,
    "pos_geral_categoria": 2
  },
  {
    "atleta": "Onaldo Dantas",
    "academia": "AABB",
    "equipe": "MASTER",
    "categoria": "Masculino",
    "ftp_final": "00:00:16",
    "ftp_final_s": 16,
    "montanha": "00:25:45",
    "montanha_s": 1545,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": "00:26:01",
    "tempo_total_s": 1561,
    "provas": 2,
    "completo": false,
    "pontos_ftp": 5,
    "pos_ftp": 9,
    "pontos_montanha": 9,
    "pos_montanha": 7,
    "pontos_ld30k": 0,
    "pos_ld30k": null,
    "pontos_total": 14,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "Alberto",
    "academia": "PULSE",
    "equipe": "MASTER",
    "categoria": "Masculino",
    "ftp_final": "00:00:18",
    "ftp_final_s": 18,
    "montanha": "00:25:17",
    "montanha_s": 1517,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:48:24",
    "ld30k_s": 2904,
    "tempo_total": "01:13:59",
    "tempo_total_s": 4439,
    "provas": 3,
    "completo": true,
    "pontos_ftp": 0,
    "pos_ftp": 13,
    "pontos_montanha": 13,
    "pos_montanha": 5,
    "pontos_ld30k": 13,
    "pos_ld30k": 5,
    "pontos_total": 26,
    "pos_geral": 13,
    "pos_geral_categoria": 2
  },
  {
    "atleta": "Luerber Oscar",
    "academia": "PULSE",
    "equipe": "PRO MASCULINO",
    "categoria": "Masculino",
    "ftp_final": "00:00:15",
    "ftp_final_s": 15,
    "montanha": "00:25:34",
    "montanha_s": 1534,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:48:12",
    "ld30k_s": 2892,
    "tempo_total": "01:14:01",
    "tempo_total_s": 4441,
    "provas": 3,
    "completo": true,
    "pontos_ftp": 9,
    "pos_ftp": 7,
    "pontos_montanha": 9,
    "pos_montanha": 7,
    "pontos_ld30k": 9,
    "pos_ld30k": 7,
    "pontos_total": 27,
    "pos_geral": 14,
    "pos_geral_categoria": 4
  },
  {
    "atleta": "Gisele",
    "academia": "PULSE",
    "equipe": "ELITE FEMININO",
    "categoria": "Feminino",
    "ftp_final": "00:00:17",
    "ftp_final_s": 17,
    "montanha": null,
    "montanha_s": null,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": "00:00:17",
    "tempo_total_s": 17,
    "provas": 1,
    "completo": false,
    "pontos_ftp": 0,
    "pos_ftp": 12,
    "pontos_montanha": 0,
    "pos_montanha": null,
    "pontos_ld30k": 0,
    "pos_ld30k": null,
    "pontos_total": 0,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "EDUARDO",
    "academia": "BT TIROL",
    "equipe": "ELITE MASCULINO",
    "categoria": "Masculino",
    "ftp_final": "00:00:17",
    "ftp_final_s": 17,
    "montanha": null,
    "montanha_s": null,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": "00:00:17",
    "tempo_total_s": 17,
    "provas": 1,
    "completo": false,
    "pontos_ftp": 1,
    "pos_ftp": 11,
    "pontos_montanha": 0,
    "pos_montanha": null,
    "pontos_ld30k": 0,
    "pos_ld30k": null,
    "pontos_total": 1,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "Luciana Maria",
    "academia": "AABB",
    "equipe": "SUB-26",
    "categoria": "Feminino",
    "ftp_final": "00:00:19",
    "ftp_final_s": 19,
    "montanha": "00:28:31",
    "montanha_s": 1711,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:54:27",
    "ld30k_s": 3267,
    "tempo_total": "01:23:17",
    "tempo_total_s": 4997,
    "provas": 3,
    "completo": true,
    "pontos_ftp": 3,
    "pos_ftp": 10,
    "pontos_montanha": 7,
    "pos_montanha": 8,
    "pontos_ld30k": 0,
    "pos_ld30k": 12,
    "pontos_total": 10,
    "pos_geral": 20,
    "pos_geral_categoria": 6
  },
  {
    "atleta": "Wilson Chacon",
    "academia": "BT TIROL",
    "equipe": "MASTER",
    "categoria": "Masculino",
    "ftp_final": "00:00:17",
    "ftp_final_s": 17,
    "montanha": null,
    "montanha_s": null,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:49:00",
    "ld30k_s": 2940,
    "tempo_total": "00:49:17",
    "tempo_total_s": 2957,
    "provas": 2,
    "completo": false,
    "pontos_ftp": 1,
    "pos_ftp": 11,
    "pontos_montanha": 0,
    "pos_montanha": null,
    "pontos_ld30k": 11,
    "pos_ld30k": 6,
    "pontos_total": 12,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "Rogério Dantas",
    "academia": "BT NS",
    "equipe": "MASTER",
    "categoria": "Masculino",
    "ftp_final": "00:00:17",
    "ftp_final_s": 17,
    "montanha": "00:28:21",
    "montanha_s": 1701,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": "00:28:38",
    "tempo_total_s": 1718,
    "provas": 2,
    "completo": false,
    "pontos_ftp": 0,
    "pos_ftp": 12,
    "pontos_montanha": 5,
    "pos_montanha": 9,
    "pontos_ld30k": 0,
    "pos_ld30k": null,
    "pontos_total": 5,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "Dowglas",
    "academia": "BT NS",
    "equipe": "PRO MASCULINO",
    "categoria": "Masculino",
    "ftp_final": "00:00:18",
    "ftp_final_s": 18,
    "montanha": null,
    "montanha_s": null,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": "00:00:18",
    "tempo_total_s": 18,
    "provas": 1,
    "completo": false,
    "pontos_ftp": 3,
    "pos_ftp": 10,
    "pontos_montanha": 0,
    "pos_montanha": null,
    "pontos_ld30k": 0,
    "pos_ld30k": null,
    "pontos_total": 3,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "Vivi",
    "academia": "PULSE",
    "equipe": "PRO FEMININO",
    "categoria": "Feminino",
    "ftp_final": "00:00:18",
    "ftp_final_s": 18,
    "montanha": "00:30:32",
    "montanha_s": 1832,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": "00:30:50",
    "tempo_total_s": 1850,
    "provas": 2,
    "completo": false,
    "pontos_ftp": 3,
    "pos_ftp": 10,
    "pontos_montanha": 1,
    "pos_montanha": 11,
    "pontos_ld30k": 0,
    "pos_ld30k": null,
    "pontos_total": 4,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "Laura Negreiros",
    "academia": "AABB",
    "equipe": "SUB-26",
    "categoria": "Feminino",
    "ftp_final": "00:00:20",
    "ftp_final_s": 20,
    "montanha": "00:29:43",
    "montanha_s": 1783,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:53:19",
    "ld30k_s": 3199,
    "tempo_total": "01:23:22",
    "tempo_total_s": 5002,
    "provas": 3,
    "completo": true,
    "pontos_ftp": 1,
    "pos_ftp": 11,
    "pontos_montanha": 1,
    "pos_montanha": 11,
    "pontos_ld30k": 3,
    "pos_ld30k": 10,
    "pontos_total": 5,
    "pos_geral": 21,
    "pos_geral_categoria": 7
  },
  {
    "atleta": "Fernanda Fernandes",
    "academia": "AABB",
    "equipe": "MASTER",
    "categoria": "Feminino",
    "ftp_final": "00:00:20",
    "ftp_final_s": 20,
    "montanha": "00:30:19",
    "montanha_s": 1819,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": "00:30:39",
    "tempo_total_s": 1839,
    "provas": 2,
    "completo": false,
    "pontos_ftp": 0,
    "pos_ftp": 14,
    "pontos_montanha": 0,
    "pos_montanha": 14,
    "pontos_ld30k": 0,
    "pos_ld30k": null,
    "pontos_total": 0,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "João Menezes",
    "academia": "AABB",
    "equipe": "SUB-26",
    "categoria": "Masculino",
    "ftp_final": "00:00:11",
    "ftp_final_s": 11,
    "montanha": "00:25:52",
    "montanha_s": 1552,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:48:58",
    "ld30k_s": 2938,
    "tempo_total": "01:15:01",
    "tempo_total_s": 4501,
    "provas": 3,
    "completo": true,
    "pontos_ftp": 20,
    "pos_ftp": 2,
    "pontos_montanha": 15,
    "pos_montanha": 4,
    "pontos_ld30k": 13,
    "pos_ld30k": 5,
    "pontos_total": 48,
    "pos_geral": 15,
    "pos_geral_categoria": 3
  },
  {
    "atleta": "Matheus Alves",
    "academia": "BT NS",
    "equipe": "SUB-26",
    "categoria": "Masculino",
    "ftp_final": "00:00:18",
    "ftp_final_s": 18,
    "montanha": null,
    "montanha_s": null,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:52:13",
    "ld30k_s": 3133,
    "tempo_total": "00:52:31",
    "tempo_total_s": 3151,
    "provas": 2,
    "completo": false,
    "pontos_ftp": 5,
    "pos_ftp": 9,
    "pontos_montanha": 0,
    "pos_montanha": null,
    "pontos_ld30k": 7,
    "pos_ld30k": 8,
    "pontos_total": 12,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "JESSICA",
    "academia": "BT NS",
    "equipe": "SUB-26",
    "categoria": "Feminino",
    "ftp_final": "00:00:20",
    "ftp_final_s": 20,
    "montanha": null,
    "montanha_s": null,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": "00:00:20",
    "tempo_total_s": 20,
    "provas": 1,
    "completo": false,
    "pontos_ftp": 0,
    "pos_ftp": 12,
    "pontos_montanha": 0,
    "pos_montanha": null,
    "pontos_ld30k": 0,
    "pos_ld30k": null,
    "pontos_total": 0,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "Giuly Giardinni",
    "academia": "AABB",
    "equipe": "PRO FEMININO",
    "categoria": "Feminino",
    "ftp_final": "00:00:42",
    "ftp_final_s": 42,
    "montanha": "00:28:07",
    "montanha_s": 1687,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:54:40",
    "ld30k_s": 3280,
    "tempo_total": "01:23:29",
    "tempo_total_s": 5009,
    "provas": 3,
    "completo": true,
    "pontos_ftp": 0,
    "pos_ftp": 13,
    "pontos_montanha": 17,
    "pos_montanha": 3,
    "pontos_ld30k": 5,
    "pos_ld30k": 9,
    "pontos_total": 22,
    "pos_geral": 22,
    "pos_geral_categoria": 7
  },
  {
    "atleta": "Elistenio Pai",
    "academia": "BT TIROL",
    "equipe": "PRO MASCULINO",
    "categoria": "Masculino",
    "ftp_final": "00:00:19",
    "ftp_final_s": 19,
    "montanha": "00:26:42",
    "montanha_s": 1602,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": "00:27:01",
    "tempo_total_s": 1621,
    "provas": 2,
    "completo": false,
    "pontos_ftp": 1,
    "pos_ftp": 11,
    "pontos_montanha": 3,
    "pos_montanha": 10,
    "pontos_ld30k": 0,
    "pos_ld30k": null,
    "pontos_total": 4,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "Fernanda Veloso",
    "academia": "PULSE",
    "equipe": "PRO FEMININO",
    "categoria": "Feminino",
    "ftp_final": "00:00:21",
    "ftp_final_s": 21,
    "montanha": "00:30:00",
    "montanha_s": 1800,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": "00:30:21",
    "tempo_total_s": 1821,
    "provas": 2,
    "completo": false,
    "pontos_ftp": 0,
    "pos_ftp": 12,
    "pontos_montanha": 3,
    "pos_montanha": 10,
    "pontos_ld30k": 0,
    "pos_ld30k": null,
    "pontos_total": 3,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "Katia Cunha",
    "academia": "PULSE",
    "equipe": "MASTER",
    "categoria": "Feminino",
    "ftp_final": "00:00:16",
    "ftp_final_s": 16,
    "montanha": "00:28:03",
    "montanha_s": 1683,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:55:30",
    "ld30k_s": 3330,
    "tempo_total": "01:23:49",
    "tempo_total_s": 5029,
    "provas": 3,
    "completo": true,
    "pontos_ftp": 3,
    "pos_ftp": 10,
    "pontos_montanha": 7,
    "pos_montanha": 8,
    "pontos_ld30k": 0,
    "pos_ld30k": 14,
    "pontos_total": 10,
    "pos_geral": 23,
    "pos_geral_categoria": 5
  },
  {
    "atleta": "GERUSIA",
    "academia": "BT NS",
    "equipe": "MASTER",
    "categoria": "Feminino",
    "ftp_final": "00:00:21",
    "ftp_final_s": 21,
    "montanha": null,
    "montanha_s": null,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:53:40",
    "ld30k_s": 3220,
    "tempo_total": "00:54:01",
    "tempo_total_s": 3241,
    "provas": 2,
    "completo": false,
    "pontos_ftp": 0,
    "pos_ftp": 16,
    "pontos_montanha": 0,
    "pos_montanha": null,
    "pontos_ld30k": 0,
    "pos_ld30k": 13,
    "pontos_total": 0,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "Maurício",
    "academia": "PULSE",
    "equipe": "MASTER",
    "categoria": "Masculino",
    "ftp_final": "00:00:20",
    "ftp_final_s": 20,
    "montanha": null,
    "montanha_s": null,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:51:31",
    "ld30k_s": 3091,
    "tempo_total": "00:51:51",
    "tempo_total_s": 3111,
    "provas": 2,
    "completo": false,
    "pontos_ftp": 0,
    "pos_ftp": 15,
    "pontos_montanha": 0,
    "pos_montanha": null,
    "pontos_ld30k": 5,
    "pos_ld30k": 9,
    "pontos_total": 5,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "Chiyo da Silva",
    "academia": "AABB",
    "equipe": "MASTER",
    "categoria": "Feminino",
    "ftp_final": "00:00:13",
    "ftp_final_s": 13,
    "montanha": "00:30:50",
    "montanha_s": 1850,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:56:50",
    "ld30k_s": 3410,
    "tempo_total": "01:27:53",
    "tempo_total_s": 5273,
    "provas": 3,
    "completo": true,
    "pontos_ftp": 17,
    "pos_ftp": 3,
    "pontos_montanha": 0,
    "pos_montanha": 15,
    "pontos_ld30k": 0,
    "pos_ld30k": 16,
    "pontos_total": 17,
    "pos_geral": 24,
    "pos_geral_categoria": 6
  },
  {
    "atleta": "Carol Negreiros",
    "academia": "PULSE",
    "equipe": "SUB-26",
    "categoria": "Feminino",
    "ftp_final": "00:00:22",
    "ftp_final_s": 22,
    "montanha": "00:32:27",
    "montanha_s": 1947,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "01:07:11",
    "ld30k_s": 4031,
    "tempo_total": "01:40:00",
    "tempo_total_s": 6000,
    "provas": 3,
    "completo": true,
    "pontos_ftp": 0,
    "pos_ftp": 13,
    "pontos_montanha": 0,
    "pos_montanha": 16,
    "pontos_ld30k": 0,
    "pos_ld30k": 16,
    "pontos_total": 0,
    "pos_geral": 25,
    "pos_geral_categoria": 8
  },
  {
    "atleta": "Artur Sena",
    "academia": "BT NS",
    "equipe": "SUB-26",
    "categoria": "Masculino",
    "ftp_final": "00:00:22",
    "ftp_final_s": 22,
    "montanha": "00:28:04",
    "montanha_s": 1684,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": "00:28:26",
    "tempo_total_s": 1706,
    "provas": 2,
    "completo": false,
    "pontos_ftp": 0,
    "pos_ftp": 14,
    "pontos_montanha": 9,
    "pos_montanha": 7,
    "pontos_ld30k": 0,
    "pos_ld30k": null,
    "pontos_total": 9,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "Maria Karolina",
    "academia": "BT TIROL",
    "equipe": "PRO FEMININO",
    "categoria": "Feminino",
    "ftp_final": null,
    "ftp_final_s": null,
    "montanha": "00:30:47",
    "montanha_s": 1847,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:54:46",
    "ld30k_s": 3286,
    "tempo_total": "01:25:33",
    "tempo_total_s": 5133,
    "provas": 2,
    "completo": false,
    "pontos_ftp": 0,
    "pos_ftp": null,
    "pontos_montanha": 0,
    "pos_montanha": 12,
    "pontos_ld30k": 3,
    "pos_ld30k": 10,
    "pontos_total": 3,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "Luiz César",
    "academia": "AABB",
    "equipe": "SUB-26",
    "categoria": "Masculino",
    "ftp_final": "00:00:23",
    "ftp_final_s": 23,
    "montanha": null,
    "montanha_s": null,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": null,
    "ld30k_s": null,
    "tempo_total": "00:00:23",
    "tempo_total_s": 23,
    "provas": 1,
    "completo": false,
    "pontos_ftp": 0,
    "pos_ftp": 15,
    "pontos_montanha": 0,
    "pos_montanha": null,
    "pontos_ld30k": 0,
    "pos_ld30k": null,
    "pontos_total": 0,
    "pos_geral": null,
    "pos_geral_categoria": null
  },
  {
    "atleta": "Danilo Vale",
    "academia": "BT TIROL",
    "equipe": "ELITE MASCULINO",
    "categoria": "Masculino",
    "ftp_final": null,
    "ftp_final_s": null,
    "montanha": "00:23:55",
    "montanha_s": 1435,
    "cr10k": null,
    "cr10k_s": null,
    "ld30k": "00:44:28",
    "ld30k_s": 2668,
    "tempo_total": "01:08:23",
    "tempo_total_s": 4103,
    "provas": 2,
    "completo": false,
    "pontos_ftp": 0,
    "pos_ftp": null,
    "pontos_montanha": 7,
    "pos_montanha": 8,
    "pontos_ld30k": 7,
    "pos_ld30k": 8,
    "pontos_total": 14,
    "pos_geral": null,
    "pos_geral_categoria": null
  }
];

const PONTOS_EQUIPE_CAT = {
  "ELITE FEMININO": {
    "FTP Final": {
      "BT NS": {
        "soma_s": 25,
        "atletas": [
          "Simone Ribeiro",
          "Alini Brito",
          "Joyce Ribeiro"
        ],
        "pontos": 25,
        "posicao": 1,
        "soma_str": "00:00:25"
      },
      "BT TIROL": {
        "soma_s": 39,
        "atletas": [
          "Andréia Medeiros",
          "Jannaina Queiroz",
          "Renata Seixas"
        ],
        "pontos": 17,
        "posicao": 3,
        "soma_str": "00:00:39"
      },
      "AABB": {
        "soma_s": 34,
        "atletas": [
          "Sarah Brito",
          "Silvia Drummond",
          "Oona Lopes"
        ],
        "pontos": 20,
        "posicao": 2,
        "soma_str": "00:00:34"
      },
      "PULSE": {
        "soma_s": 46,
        "atletas": [
          "Hívila Moreira",
          "Karine Symonir",
          "Gisele"
        ],
        "pontos": 15,
        "posicao": 4,
        "soma_str": "00:00:46"
      }
    },
    "Montanha": {
      "PULSE": {
        "soma_s": 4901,
        "atletas": [
          "Cris Diniz",
          "Hívila Moreira",
          "Karine Symonir"
        ],
        "pontos": 17,
        "posicao": 3,
        "soma_str": "01:21:41"
      },
      "AABB": {
        "soma_s": 5000,
        "atletas": [
          "Sarah Brito",
          "Silvia Drummond",
          "Lydia Tinôco"
        ],
        "pontos": 15,
        "posicao": 4,
        "soma_str": "01:23:20"
      },
      "BT TIROL": {
        "soma_s": 4801,
        "atletas": [
          "Andréia Medeiros",
          "Renata Seixas",
          "Raissa Georgia"
        ],
        "pontos": 20,
        "posicao": 2,
        "soma_str": "01:20:01"
      },
      "BT NS": {
        "soma_s": 4775,
        "atletas": [
          "Alini Brito",
          "Simone Ribeiro",
          "Joyce Ribeiro"
        ],
        "pontos": 25,
        "posicao": 1,
        "soma_str": "01:19:35"
      }
    },
    "Longa Distância 30k": {
      "PULSE": {
        "soma_s": 9109,
        "atletas": [
          "Cris Diniz",
          "Karine Symonir",
          "Hívila Moreira"
        ],
        "pontos": 17,
        "posicao": 3,
        "soma_str": "02:31:49"
      },
      "AABB": {
        "soma_s": 9134,
        "atletas": [
          "Silvia Drummond",
          "Sarah Brito",
          "Lydia Tinôco"
        ],
        "pontos": 15,
        "posicao": 4,
        "soma_str": "02:32:14"
      },
      "BT TIROL": {
        "soma_s": 8922,
        "atletas": [
          "Andréia Medeiros",
          "Renata Seixas",
          "Raissa Georgia"
        ],
        "pontos": 20,
        "posicao": 2,
        "soma_str": "02:28:42"
      },
      "BT NS": {
        "soma_s": 8677,
        "atletas": [
          "Joyce Ribeiro",
          "Simone Ribeiro",
          "Alini Brito"
        ],
        "pontos": 25,
        "posicao": 1,
        "soma_str": "02:24:37"
      }
    }
  },
  "ELITE MASCULINO": {
    "FTP Final": {
      "BT NS": {
        "soma_s": 26,
        "atletas": [
          "Omar Dantas",
          "Gringo"
        ],
        "pontos": 20,
        "posicao": 2,
        "soma_str": "00:00:26"
      },
      "BT TIROL": {
        "soma_s": 37,
        "atletas": [
          "Sergio Torralba",
          "Fabrício Barros",
          "EDUARDO"
        ],
        "pontos": 15,
        "posicao": 4,
        "soma_str": "00:00:37"
      },
      "PULSE": {
        "soma_s": 24,
        "atletas": [
          "Diogo Almeida",
          "Elionai",
          "Lucas Leonardo"
        ],
        "pontos": 25,
        "posicao": 1,
        "soma_str": "00:00:24"
      },
      "AABB": {
        "soma_s": 33,
        "atletas": [
          "Bira Carratu",
          "Renato Araújo",
          "Genival Ferreira"
        ],
        "pontos": 17,
        "posicao": 3,
        "soma_str": "00:00:33"
      }
    },
    "Montanha": {
      "BT NS": {
        "soma_s": 4297,
        "atletas": [
          "Omar Dantas",
          "Neto Xavier",
          "Gringo"
        ],
        "pontos": 20,
        "posicao": 2,
        "soma_str": "01:11:37"
      },
      "PULSE": {
        "soma_s": 4299,
        "atletas": [
          "Lucas Leonardo",
          "Diogo Almeida",
          "Rafael Povoas"
        ],
        "pontos": 17,
        "posicao": 3,
        "soma_str": "01:11:39"
      },
      "AABB": {
        "soma_s": 4186,
        "atletas": [
          "Sivonaldo Tercio",
          "Genival Ferreira",
          "Bira Carratu"
        ],
        "pontos": 25,
        "posicao": 1,
        "soma_str": "01:09:46"
      },
      "BT TIROL": {
        "soma_s": 4319,
        "atletas": [
          "Sergio Torralba",
          "Danilo Vale",
          "Fabrício Barros"
        ],
        "pontos": 15,
        "posicao": 4,
        "soma_str": "01:11:59"
      }
    },
    "Longa Distância 30k": {
      "BT NS": {
        "soma_s": 7841,
        "atletas": [
          "Omar Dantas",
          "Daniel Azevedo",
          "Neto Xavier"
        ],
        "pontos": 25,
        "posicao": 1,
        "soma_str": "02:10:41"
      },
      "PULSE": {
        "soma_s": 7846,
        "atletas": [
          "Elionai",
          "Lucas Leonardo",
          "Rafael Povoas"
        ],
        "pontos": 20,
        "posicao": 2,
        "soma_str": "02:10:46"
      },
      "AABB": {
        "soma_s": 8114,
        "atletas": [
          "Sivonaldo Tercio",
          "Genival Ferreira",
          "Renato Araújo"
        ],
        "pontos": 15,
        "posicao": 4,
        "soma_str": "02:15:14"
      },
      "BT TIROL": {
        "soma_s": 7956,
        "atletas": [
          "Sergio Torralba",
          "Danilo Vale",
          "Fabrício Barros"
        ],
        "pontos": 17,
        "posicao": 3,
        "soma_str": "02:12:36"
      }
    }
  },
  "PRO FEMININO": {
    "FTP Final": {
      "BT TIROL": {
        "soma_s": 44,
        "atletas": [
          "Heloisa Lopes",
          "Vanessa Rodrigues",
          "Andreia Araujo"
        ],
        "pontos": 17,
        "posicao": 3,
        "soma_str": "00:00:44"
      },
      "AABB": {
        "soma_s": 40,
        "atletas": [
          "Allyne França",
          "Camila Mota",
          "Helena Jales"
        ],
        "pontos": 20,
        "posicao": 2,
        "soma_str": "00:00:40"
      },
      "BT NS": {
        "soma_s": 39,
        "atletas": [
          "Isadora Meybel",
          "Beatriz Bezerra",
          "Renata Ivia"
        ],
        "pontos": 25,
        "posicao": 1,
        "soma_str": "00:00:39"
      },
      "PULSE": {
        "soma_s": 49,
        "atletas": [
          "Ana Azevedo",
          "Vivi",
          "Fernanda Veloso"
        ],
        "pontos": 15,
        "posicao": 4,
        "soma_str": "00:00:49"
      }
    },
    "Montanha": {
      "BT NS": {
        "soma_s": 5104,
        "atletas": [
          "Lívia Revoredo",
          "Beatriz Bezerra",
          "Isadora Meybel"
        ],
        "pontos": 25,
        "posicao": 1,
        "soma_str": "01:25:04"
      },
      "BT TIROL": {
        "soma_s": 5276,
        "atletas": [
          "Andreia Araujo",
          "Vanessa Rodrigues",
          "Maria Karolina"
        ],
        "pontos": 17,
        "posicao": 3,
        "soma_str": "01:27:56"
      },
      "AABB": {
        "soma_s": 5161,
        "atletas": [
          "Giuly Giardinni",
          "Camila Mota",
          "Allyne França"
        ],
        "pontos": 20,
        "posicao": 2,
        "soma_str": "01:26:01"
      },
      "PULSE": {
        "soma_s": 5356,
        "atletas": [
          "Ana Azevedo",
          "Fernanda Veloso",
          "Vivi"
        ],
        "pontos": 15,
        "posicao": 4,
        "soma_str": "01:29:16"
      }
    },
    "Longa Distância 30k": {
      "PULSE": {
        "soma_s": 6800,
        "atletas": [
          "Ana Azevedo",
          "Adriana Melo"
        ],
        "pontos": 25,
        "posicao": 1,
        "soma_str": "01:53:20"
      },
      "BT NS": {
        "soma_s": 9309,
        "atletas": [
          "Lívia Revoredo",
          "Isadora Meybel",
          "Beatriz Bezerra"
        ],
        "pontos": 20,
        "posicao": 2,
        "soma_str": "02:35:09"
      },
      "BT TIROL": {
        "soma_s": 9652,
        "atletas": [
          "Andreia Araujo",
          "Heloisa Lopes",
          "Maria Karolina"
        ],
        "pontos": 15,
        "posicao": 4,
        "soma_str": "02:40:52"
      },
      "AABB": {
        "soma_s": 9634,
        "atletas": [
          "Camila Mota",
          "Allyne França",
          "Giuly Giardinni"
        ],
        "pontos": 17,
        "posicao": 3,
        "soma_str": "02:40:34"
      }
    }
  },
  "PRO MASCULINO": {
    "FTP Final": {
      "AABB": {
        "soma_s": 36,
        "atletas": [
          "Bruno Cabral",
          "José Arimatéia",
          "César Maia"
        ],
        "pontos": 20,
        "posicao": 2,
        "soma_str": "00:00:36"
      },
      "PULSE": {
        "soma_s": 39,
        "atletas": [
          "Arthur Dantas",
          "Olisuel Pereira",
          "Luerber Oscar"
        ],
        "pontos": 17,
        "posicao": 3,
        "soma_str": "00:00:39"
      },
      "BT TIROL": {
        "soma_s": 29,
        "atletas": [
          "Carlos Thompson",
          "Elistenio Pai"
        ],
        "pontos": 25,
        "posicao": 1,
        "soma_str": "00:00:29"
      },
      "BT NS": {
        "soma_s": 48,
        "atletas": [
          "Washington Filho",
          "Edu Silva",
          "Dowglas"
        ],
        "pontos": 15,
        "posicao": 4,
        "soma_str": "00:00:48"
      }
    },
    "Montanha": {
      "AABB": {
        "soma_s": 4470,
        "atletas": [
          "Bruno Cabral",
          "José Arimatéia",
          "Haroldo Duarte"
        ],
        "pontos": 20,
        "posicao": 2,
        "soma_str": "01:14:30"
      },
      "BT TIROL": {
        "soma_s": 4861,
        "atletas": [
          "Carlos Thompson",
          "Elistenio Pai",
          "Igor Rosado"
        ],
        "pontos": 15,
        "posicao": 4,
        "soma_str": "01:21:01"
      },
      "BT NS": {
        "soma_s": 3057,
        "atletas": [
          "Washington Filho",
          "Kleber Gentil"
        ],
        "pontos": 25,
        "posicao": 1,
        "soma_str": "00:50:57"
      },
      "PULSE": {
        "soma_s": 4505,
        "atletas": [
          "Arthur Dantas",
          "Olisuel Pereira",
          "Luerber Oscar"
        ],
        "pontos": 17,
        "posicao": 3,
        "soma_str": "01:15:05"
      }
    },
    "Longa Distância 30k": {
      "AABB": {
        "soma_s": 8400,
        "atletas": [
          "César Maia",
          "José Arimatéia",
          "Haroldo Duarte"
        ],
        "pontos": 25,
        "posicao": 1,
        "soma_str": "02:20:00"
      },
      "BT NS": {
        "soma_s": 8752,
        "atletas": [
          "Edu Silva",
          "Washington Filho",
          "Kleber Gentil"
        ],
        "pontos": 17,
        "posicao": 3,
        "soma_str": "02:25:52"
      },
      "PULSE": {
        "soma_s": 8525,
        "atletas": [
          "Olisuel Pereira",
          "Luerber Oscar",
          "Luiz Marcelo"
        ],
        "pontos": 20,
        "posicao": 2,
        "soma_str": "02:22:05"
      }
    }
  },
  "MASTER": {
    "FTP Final": {
      "BT TIROL": {
        "soma_s": 63,
        "atletas": [
          "Ana P. Mendes",
          "CLAUDIA REGINA",
          "Orlando Cunha",
          "Wilson Chacon"
        ],
        "pontos": 25,
        "posicao": 1,
        "soma_str": "00:01:03"
      },
      "PULSE": {
        "soma_s": 63,
        "atletas": [
          "LIEGE",
          "Katia Cunha",
          "Alberto",
          "Maurício"
        ],
        "pontos": 20,
        "posicao": 2,
        "soma_str": "00:01:03"
      },
      "BT NS": {
        "soma_s": 63,
        "atletas": [
          "Raimundo Romão",
          "Socorro Linhares",
          "Rogério Dantas",
          "GERUSIA"
        ],
        "pontos": 17,
        "posicao": 3,
        "soma_str": "00:01:03"
      },
      "AABB": {
        "soma_s": 64,
        "atletas": [
          "Chiyo da Silva",
          "Armando Nóbrega",
          "Onaldo Dantas",
          "Fernanda Fernandes"
        ],
        "pontos": 15,
        "posicao": 4,
        "soma_str": "00:01:04"
      }
    },
    "Montanha": {
      "PULSE": {
        "soma_s": 6477,
        "atletas": [
          "Daniel Freire",
          "Alberto",
          "Katia Cunha",
          "Alê Agra"
        ],
        "pontos": 25,
        "posicao": 1,
        "soma_str": "01:47:57"
      },
      "BT NS": {
        "soma_s": 6617,
        "atletas": [
          "Arthur Martins",
          "Rogério Dantas",
          "Alzinalia Lopes",
          "Socorro Linhares"
        ],
        "pontos": 17,
        "posicao": 3,
        "soma_str": "01:50:17"
      },
      "BT TIROL": {
        "soma_s": 6596,
        "atletas": [
          "Orlando Cunha",
          "André Fernandes",
          "Ana P. Mendes",
          "Sanzia Melo"
        ],
        "pontos": 20,
        "posicao": 2,
        "soma_str": "01:49:56"
      },
      "AABB": {
        "soma_s": 6734,
        "atletas": [
          "César Britto",
          "Onaldo Dantas",
          "Fernanda Fernandes",
          "Chiyo da Silva"
        ],
        "pontos": 15,
        "posicao": 4,
        "soma_str": "01:52:14"
      }
    },
    "Longa Distância 30k": {
      "BT NS": {
        "soma_s": 11680,
        "atletas": [
          "Raimundo Romão",
          "Arthur Martins",
          "Socorro Linhares",
          "GERUSIA"
        ],
        "pontos": 25,
        "posicao": 1,
        "soma_str": "03:14:40"
      },
      "AABB": {
        "soma_s": 12536,
        "atletas": [
          "César Britto",
          "Armando Nóbrega",
          "Sheila Sales",
          "Chiyo da Silva"
        ],
        "pontos": 15,
        "posicao": 4,
        "soma_str": "03:28:56"
      },
      "BT TIROL": {
        "soma_s": 12137,
        "atletas": [
          "Orlando Cunha",
          "Wilson Chacon",
          "Ana P. Mendes",
          "CLAUDIA REGINA"
        ],
        "pontos": 20,
        "posicao": 2,
        "soma_str": "03:22:17"
      },
      "PULSE": {
        "soma_s": 12339,
        "atletas": [
          "Alberto",
          "LIEGE",
          "Maurício",
          "Katia Cunha"
        ],
        "pontos": 17,
        "posicao": 3,
        "soma_str": "03:25:39"
      }
    }
  },
  "SUB-26": {
    "FTP Final": {
      "BT TIROL": {
        "soma_s": 50,
        "atletas": [
          "Duduzinho",
          "Lucas Eurípides",
          "Luna Melo"
        ],
        "pontos": 25,
        "posicao": 1,
        "soma_str": "00:00:50"
      },
      "PULSE": {
        "soma_s": 60,
        "atletas": [
          "Júlia Rocha",
          "José Wilson",
          "Victor Barbosa",
          "Carol Negreiros"
        ],
        "pontos": 20,
        "posicao": 2,
        "soma_str": "00:01:00"
      },
      "BT NS": {
        "soma_s": 75,
        "atletas": [
          "Livia Darc",
          "Matheus Alves",
          "JESSICA",
          "Artur Sena"
        ],
        "pontos": 15,
        "posicao": 4,
        "soma_str": "00:01:15"
      },
      "AABB": {
        "soma_s": 73,
        "atletas": [
          "João Menezes",
          "Luciana Maria",
          "Laura Negreiros",
          "Luiz César"
        ],
        "pontos": 17,
        "posicao": 3,
        "soma_str": "00:01:13"
      }
    },
    "Montanha": {
      "AABB": {
        "soma_s": 6707,
        "atletas": [
          "João Menezes",
          "Allan Oliveira",
          "Luciana Maria",
          "Laura Negreiros"
        ],
        "pontos": 25,
        "posicao": 1,
        "soma_str": "01:51:47"
      },
      "BT TIROL": {
        "soma_s": 7009,
        "atletas": [
          "Lucas Eurípides",
          "Isabel Lucena",
          "Elistenio Filho",
          "Luna Melo"
        ],
        "pontos": 15,
        "posicao": 4,
        "soma_str": "01:56:49"
      },
      "PULSE": {
        "soma_s": 6796,
        "atletas": [
          "Victor Barbosa",
          "Francisco Vito",
          "Júlia Rocha",
          "Carol Negreiros"
        ],
        "pontos": 20,
        "posicao": 2,
        "soma_str": "01:53:16"
      },
      "BT NS": {
        "soma_s": 6799,
        "atletas": [
          "Joao Pedro",
          "Artur Sena",
          "Livia Darc",
          "Samara Silva"
        ],
        "pontos": 17,
        "posicao": 3,
        "soma_str": "01:53:19"
      }
    },
    "Longa Distância 30k": {
      "AABB": {
        "soma_s": 12541,
        "atletas": [
          "João Menezes",
          "Allan Oliveira",
          "Laura Negreiros",
          "Luciana Maria"
        ],
        "pontos": 25,
        "posicao": 1,
        "soma_str": "03:29:01"
      },
      "BT TIROL": {
        "soma_s": 12720,
        "atletas": [
          "Lucas Eurípides",
          "Maria J nobrega",
          "Isabel Lucena",
          "Duduzinho"
        ],
        "pontos": 17,
        "posicao": 3,
        "soma_str": "03:32:00"
      },
      "BT NS": {
        "soma_s": 12578,
        "atletas": [
          "Joao Pedro",
          "Livia Darc",
          "Matheus Alves",
          "Samara Silva"
        ],
        "pontos": 20,
        "posicao": 2,
        "soma_str": "03:29:38"
      },
      "PULSE": {
        "soma_s": 12980,
        "atletas": [
          "José Wilson",
          "Victor Barbosa",
          "Júlia Rocha",
          "Carol Negreiros"
        ],
        "pontos": 15,
        "posicao": 4,
        "soma_str": "03:36:20"
      }
    }
  }
};

const PONTOS_EQUIPE_TOTAL = {
  "BT NS": 378,
  "BT TIROL": 315,
  "AABB": 341,
  "PULSE": 337
};

const RANKING_GERAL_MASC = ["Omar Dantas", "Sergio Torralba", "Lucas Leonardo", "Neto Xavier", "Genival Ferreira", "Lucas Eurípides", "Olisuel Pereira", "José Arimatéia", "Washington Filho", "Orlando Cunha", "Fabrício Barros", "Victor Barbosa", "Alberto", "Luerber Oscar", "João Menezes"];

const RANKING_GERAL_FEM  = ["Simone Ribeiro", "Andréia Medeiros", "Alini Brito", "Joyce Ribeiro", "Renata Seixas", "Silvia Drummond", "Sarah Brito", "Andreia Araujo", "Hívila Moreira", "Karine Symonir", "Livia Darc", "Camila Mota", "Beatriz Bezerra", "Socorro Linhares", "Ana Azevedo", "Ana P. Mendes", "Isadora Meybel", "Allyne França", "Júlia Rocha", "Luciana Maria", "Laura Negreiros", "Giuly Giardinni", "Katia Cunha", "Chiyo da Silva", "Carol Negreiros"];

